import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const folder='blender/towers/copilot_octocat_2_0_lowpoly/v01';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const m=JSON.parse(await fs.readFile(folder+'/asset.json'));
const audit=JSON.parse(await fs.readFile(folder+'/validation/source_audit.json'));
const live=JSON.parse(await fs.readFile(folder+'/validation/inspector_evidence.json'));
const report=JSON.parse(await fs.readFile(folder+'/validation/report.json'));
const original=JSON.parse(await fs.readFile(folder+'/validation/original_baseline.json'));
if(hash(await fs.readFile(original.source))!==original.sourceHash || hash(await fs.readFile(original.runtime))!==original.runtimeHash)throw Error('Original changed');
if(audit.sourceHash!==m.delivery.sourceHash || !audit.passed || live.sha256!==m.delivery.sha256 || live.errors.length || !report.passed)throw Error('Stale or failed evidence');
if(m.revision!==4 || report.triangles!==3961 || report.meshes!==2)throw Error('Reviewed revision changed');
for(const e of live.evidence)if(hash(await fs.readFile(e.path))!==e.sha256)throw Error('Evidence changed');
await fs.writeFile(folder+'/validation/original_preserved.json',JSON.stringify({checkedAt:new Date().toISOString(),passed:true,...original},null,2)+'\n');
const review=JSON.parse(await fs.readFile(folder+'/validation/visual_review.json'));
review.scope='model';review.reviewedAt=new Date().toISOString();
review.checks.referenceFidelity={status:'passed',findings:'Compared original anatomy-corrected r7 runtime front/iso images and creator turnaround with the simplified registered model. Retained broad rounded head and cheeks, inset pointed ears, forehead dip, two oval eyes with glints, nose, open smile and four whiskers. All five tentacles still join beneath the head, with two arm-like limbs and three supporting tentacles in this waving upright pose. Five cups per tentacle remain. Lower-density outlines are intentionally polygonal rather than an exact smooth-sculpt match.'};
review.checks.construction={status:'passed',findings:'Personally inspected final front, right, rear, underside, close frontal/oblique face and isometric exports. Head/body source parts are each one connected closed shell with zero nonmanifold edges and degenerate faces. Cups are 25 intentionally open fitted surface patches, each with an octagonal rim and shallow centre. Initial coarse cup faces intersected skin between seated vertices; sampled triangle interiors and edges to repair clearance. Final cups show complete pale shapes without the initial holes. All three support contacts are zero. Palette geometry is consolidated into one mesh, with named source vertex groups retaining editable parts; painted head is the second mesh. Two packed images are embedded in the runtime. Runtime count is 3,961 triangles, two meshes and two materials, with nine anchors preserved.'};
review.checks.readability={status:'passed',findings:'Reviewed final phone and small game-scale captures. Large peach face, ears, contrasting eyes, waving arm, front-leg negative space and rear support in oblique views remain readable. Octagonal cups and faceted feet are deliberate simplifications; tiny glints and tongue are secondary at small scale. Retained authored approximately 1.80 m height and original palette.'};
review.checks.motion={status:'not_applicable',findings:'Static model milestone, with no rig or animation. Baseline animation remains pending in the decision record.'};
review.secondPass={status:'passed',findings:'After repairing cup/cheek seating in revision 3, consolidated palette parts for revision 4. Reviewed the finished two-mesh export again against original and creator references. Final front/oblique show intact cup surfaces and expressive face; reverse/side preserve three-support anatomy; underside preserves foot thickness and attached roots. Phone/game-scale views retain the original identity. Expected faceting remains visible in enlarged outlines and highlights; no remaining scoped seating or grounding defect blocks the low-poly model handoff.'};
review.evidence=live.evidence.map(({path,sha256,view})=>({path,sha256,view}));
review.userAcceptance={status:'pending',note:'Awaiting user feedback on the separate low-poly model revision 4.'};
review.limitations=['Static model; animation and deformation review remain pending.','Faceted outlines, simplified shallow cups and angular close-up highlights are deliberate consequences of the 4,000-triangle ceiling.','Triangle/draw-call reduction is measured; crowded gameplay performance has not been profiled.'];
await fs.writeFile(folder+'/validation/visual_review.json',JSON.stringify(review,null,2)+'\n');
const heading='## Completed low-poly review — revision 4';
let decisions=await fs.readFile(folder+'/decisions.md','utf8');
if(decisions.includes(heading))decisions=decisions.slice(0,decisions.indexOf(heading));
decisions+=`${heading}\n\nFinal: 3,961 triangles, two meshes, two materials, two embedded textures and\nno bones/clips. Reduction from the 68,180-triangle original is 94.19%. Named\npart_* vertex groups retain palette components for source editing. Head map\nremains a separate mesh/material. Nine anchors and the five construction paths\nare preserved. All three feet contact the plane at zero.\n\nRevision 2 review exposed partial cup occlusion by coarse body triangles.\nRevision 3 used triangle interior/edge sampling to clear cups and cheek patches.\nRevision 4 consolidated palette geometry. Personally inspected final front,\nside, oblique, reverse, underside, face close-ups, phone and small silhouette\nviews, then completed a second reference/attachment/readability assessment.\nTechnical validation and the source anatomy audit passed. Original source and\nruntime hashes are unchanged. User artistic acceptance remains pending.\n\nRuntime hash ${m.delivery.sha256}.\nSource hash ${m.delivery.sourceHash}.\nAnimation remains pending.\n`;
await fs.writeFile(folder+'/decisions.md',decisions);
console.log(JSON.stringify({revision:m.revision,triangles:report.triangles,meshes:report.meshes,originalPreserved:true}));
