import * as THREE from 'three';
import {GLTFLoader} from '/vendor/GLTFLoader.js';
import {mergeGeometries} from '/vendor/BufferGeometryUtils.js';
import {buildLayout,VIEWS} from './layout.js';
const $=id=>document.getElementById(id);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('stage').append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#e4ebe6');scene.fog=new THREE.Fog('#e4ebe6',115,240);
const camera=new THREE.PerspectiveCamera(38,1,.1,350);const hemi=new THREE.HemisphereLight('#f2f5f3','#91a18b',2.25);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff6df',3.2);sun.position.set(-30,60,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:55,bottom:-55,near:5,far:180});sun.shadow.bias=-.00025;sun.shadow.normalBias=.08;scene.add(sun);
const fill=new THREE.DirectionalLight('#b5d9db',.8);fill.position.set(35,20,-30);scene.add(fill);
const ground=new THREE.Mesh(new THREE.CylinderGeometry(56,58,.65,64),new THREE.MeshStandardMaterial({color:'#8ca889',roughness:.95}));ground.position.set(-1,-.48,2);ground.receiveShadow=true;scene.add(ground);
const campus=new THREE.Group();scene.add(campus);const gallery=new THREE.Group();scene.add(gallery);gallery.visible=false;
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(9,9.5,.35,48),new THREE.MeshStandardMaterial({color:'#c9d6cc',roughness:.9}));pedestal.position.y=-.28;gallery.add(pedestal);
const models=new Map(),placements=[],errors=[];let kit,parts,current='campus',selected='gh_warehouse',ready=false,night=false,secretFound=false,tapStart=null;
const orbit={target:new THREE.Vector3(-1,4,0),distance:82,theta:.66,phi:1,goal:null};let activePointer=null,lastPointer=null,pinch=null,frameMs=0,last=performance.now();
function updateCamera(){orbit.phi=THREE.MathUtils.clamp(orbit.phi,.14,1.49);orbit.distance=THREE.MathUtils.clamp(orbit.distance,3,135);const s=Math.sin(orbit.phi);camera.position.set(orbit.target.x+orbit.distance*s*Math.sin(orbit.theta),orbit.target.y+orbit.distance*Math.cos(orbit.phi),orbit.target.z+orbit.distance*s*Math.cos(orbit.theta));camera.lookAt(orbit.target);}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?55:38;camera.updateProjectionMatrix();updateCamera();}addEventListener('resize',resize);resize();
const pointers=new Map();const canvas=renderer.domElement;canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);activePointer=e.pointerId;lastPointer=[e.clientX,e.clientY];orbit.goal=null;if(pointers.size===2){const a=[...pointers.values()];pinch=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);}});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0][0]-a[1][0],a[0][1]-a[1][1]);if(pinch)orbit.distance*=pinch/d;pinch=d;return;}if(e.pointerId!==activePointer)return;const dx=e.clientX-lastPointer[0],dy=e.clientY-lastPointer[1];lastPointer=[e.clientX,e.clientY];if(e.buttons===2||e.shiftKey){const k=orbit.distance*.0017;orbit.target.x-=dx*k*Math.cos(orbit.theta);orbit.target.z+=dx*k*Math.sin(orbit.theta);orbit.target.y+=dy*k;}else{orbit.theta-=dx*.006;orbit.phi-=dy*.005;}});
canvas.addEventListener('pointerdown',e=>{tapStart=pointers.size===1?{x:e.clientX,y:e.clientY,id:e.pointerId}:null;});
canvas.addEventListener('pointerup',e=>{if(tapStart?.id===e.pointerId&&Math.hypot(e.clientX-tapStart.x,e.clientY-tapStart.y)<8)pickSecret(e.clientX,e.clientY);tapStart=null;});
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{pointers.delete(e.pointerId);activePointer=null;lastPointer=null;pinch=null;});addEventListener('blur',()=>{pointers.clear();activePointer=null;tapStart=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();orbit.goal=null;orbit.distance*=Math.exp(e.deltaY*.001);},{passive:false});
function secretScreen(){if(!parts?.secret||current!=='library')return null;const box=new THREE.Box3().setFromObject(parts.secret),point=box.getCenter(new THREE.Vector3());point.project(camera);return {x:(point.x+1)*innerWidth/2,y:(1-point.y)*innerHeight/2,visible:point.z>-1&&point.z<1&&Math.abs(point.x)<1&&Math.abs(point.y)<1};}
function pickSecret(x,y){if(!ready||current!=='library')return;const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(x/innerWidth*2-1,1-y/innerHeight*2),camera);const meshes=[];campus.traverseVisible(o=>{if(o.isMesh)meshes.push(o);});const hit=ray.intersectObjects(meshes,false)[0];let found=hit?.object;while(found&&found!==parts.secret)found=found.parent;if(found!==parts.secret)return;secretFound=true;$('secret-dialog').showModal();$('shelves').textContent='Explore shelves · ✓';}
function optimize(root){root.updateMatrixWorld(true);const boundary=root.getObjectByName('root')||root;const buckets=new Map();boundary.traverse(o=>{if(!o.isMesh)return;const mat=Array.isArray(o.material)?null:o.material;if(!mat)return;let branch=o;while(branch.parent&&branch.parent!==boundary)branch=branch.parent;const key=branch.name+'|'+mat.uuid;let bucket=buckets.get(key);if(!bucket)buckets.set(key,bucket={name:branch.name,mat,geometries:[]});const g=o.geometry.clone().applyMatrix4(o.matrixWorld);g.deleteAttribute('tangent');bucket.geometries.push(g);});const result=new THREE.Group();for(const b of buckets.values()){let geometry;try{geometry=mergeGeometries(b.geometries,false);}catch{}if(!geometry){for(const g of b.geometries){const m=new THREE.Mesh(g,b.mat);m.name=b.name;m.castShadow=true;m.receiveShadow=true;result.add(m);}continue;}const mesh=new THREE.Mesh(geometry,b.mat);mesh.name=b.name;mesh.castShadow=!b.mat.transparent;mesh.receiveShadow=true;result.add(mesh);for(const g of b.geometries)g.dispose();}return result;}
function put(id,pos=[0,0,0],rotation=0,parent=campus){const model=models.get(id).clone(true);model.position.set(...pos);model.rotation.y=rotation;model.userData.assetId=id;parent.add(model);placements.push({id,pos,rotation,model});return model;}
function instanceRepeated(parent){parent.updateMatrixWorld(true);const groups=new Map();for(const child of parent.children){const id=child.userData.assetId;if(!id)continue;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(child);}for(const [id,copies] of groups){if(copies.length<2)continue;const group=new THREE.Group();group.name=`instances-${id}`;const inverse=new THREE.Matrix4().copy(parent.matrixWorld).invert();models.get(id).children.forEach((source,index)=>{if(!source.isMesh)return;const inst=new THREE.InstancedMesh(source.geometry,source.material,copies.length);inst.name=source.name;inst.castShadow=source.castShadow;inst.receiveShadow=true;copies.forEach((copy,i)=>{copy.updateMatrixWorld(true);inst.setMatrixAt(i,new THREE.Matrix4().multiplyMatrices(inverse,copy.matrixWorld));});inst.instanceMatrix.needsUpdate=true;inst.computeBoundingSphere();group.add(inst);});copies.forEach(copy=>parent.remove(copy));parent.add(group);}}
function setVisibility(){if(!parts)return;const assetMode=current==='assets';campus.visible=!assetMode;gallery.visible=assetMode;ground.visible=!assetMode;const cut=$('cutaway').checked,showRoofs=$('roofs').checked,floor=Number($('floor').value);parts.roof.visible=showRoofs&&(!cut||current==='terrace');parts.terrace.visible=parts.roof.visible;parts.levels.forEach((g,i)=>g.visible=!cut||i===floor);const libraryFrame=parts.levels[1].getObjectByName('instances-gh_timber_frame');if(libraryFrame)libraryFrame.visible=current!=='library';parts.warehouse.traverse(o=>{const m=o.name.match(/level_(\d+)_(front|back|sides)/);if(m)o.visible=!cut||(Number(m[1])===floor&&m[2]==='back');if(o.name==='structural_corner_pilasters')o.visible=!cut;});for(const shell of [parts.atrium,parts.bridge])shell.traverse(o=>{if(o.name==='roof')o.visible=showRoofs;if(shell===parts.atrium&&(o.name==='front'||o.name==='sides'))o.visible=current!=='atrium';});$('floor-label').hidden=!cut||assetMode;$('cut-label').hidden=assetMode;$('roof-label').hidden=assetMode;}
function pose(view,immediate=false){const phoneLibrary=innerWidth<700&&current==='library';orbit.goal={target:new THREE.Vector3(...view.target),distance:view.distance*(innerWidth<700?1.5:1),theta:phoneLibrary?0:view.theta,phi:phoneLibrary?1.47:view.phi};if(immediate){Object.assign(orbit,{distance:orbit.goal.distance,theta:orbit.goal.theta,phi:orbit.goal.phi});orbit.target.copy(orbit.goal.target);orbit.goal=null;updateCamera();}}
function showAsset(id){selected=id;gallery.children.slice(1).forEach(o=>gallery.remove(o));const m=models.get(id).clone(true);gallery.add(m);const box=new THREE.Box3().setFromObject(m),size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());m.position.x-=center.x;m.position.z-=center.z;m.position.y-=box.min.y;const max=Math.max(size.x,size.y,size.z);pedestal.scale.set(Math.max(1,max/15),1,Math.max(1,max/15));const entry=kit.assets.find(a=>a.id===id);$('asset-select').value=id;$('asset-note').textContent=`${entry.name} · ${size.x.toFixed(1)} × ${size.y.toFixed(1)} × ${size.z.toFixed(1)} m. Drag to inspect every side.`;pose({...VIEWS.assets,target:[0,size.y*.45,0],distance:max*2.8});}
function setView(name,immediate=false){if(!ready||!VIEWS[name])return;current=name;const view=VIEWS[name];document.body.classList.toggle('asset-mode',name==='assets');document.body.classList.toggle('focus-view',!['campus','assets'].includes(name));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('kicker').textContent=view.kicker;$('view-title').textContent=view.title;$('view-note').textContent=name==='assets'?`Explore ${kit.assets.length} individual models for buildings, workspaces, murals and landscape.`:view.note;$('catalog').hidden=name!=='assets';$('shelves').hidden=name!=='library';$('cutaway').checked=['warehouse','library'].includes(name);$('roofs').checked=!['warehouse','library','atrium'].includes(name);if(name==='library')$('floor').value='1';if(name==='warehouse')$('floor').value='0';setVisibility();if(name==='assets')showAsset(selected);else pose(view,immediate);}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('cutaway').addEventListener('change',setVisibility);$('roofs').addEventListener('change',setVisibility);$('floor').addEventListener('change',()=>{const level=$('floor').value;if(current==='library'&&level!=='1'){setView('warehouse');$('floor').value=level;}setVisibility();if(current==='warehouse')pose({...VIEWS.warehouse,target:[-12,Number($('floor').value)*5+2,-5]});});$('reset').addEventListener('click',()=>current==='assets'?showAsset(selected):pose(current==='warehouse'&&$('cutaway').checked?{...VIEWS.warehouse,target:[-12,Number($('floor').value)*5+2,-5]}:VIEWS[current]));$('asset-select').addEventListener('change',e=>showAsset(e.target.value));$('about').addEventListener('click',()=>$('about-dialog').showModal());$('close-about').addEventListener('click',()=>$('about-dialog').close());
$('shelves').addEventListener('click',()=>{pose({target:[-25.7,6.8,-10.5],distance:4.2,theta:-.45,phi:1.38});$('view-note').textContent='Look carefully among the books. Tap any small resident you find.';});for(const id of ['close-secret','return-reading'])$(id).addEventListener('click',()=>$('secret-dialog').close());
function setNight(value){night=value;document.body.classList.toggle('night',value);$('light').textContent=value?'Daylight':'Dusk';$('light').setAttribute('aria-pressed',String(value));scene.background.set(value?'#25382d':'#e4ebe6');scene.fog.color.copy(scene.background);hemi.intensity=value?.75:2.25;sun.intensity=value?.8:3.2;fill.intensity=value?.65:.8;renderer.toneMappingExposure=value?1.4:1.25;}$('light').addEventListener('click',()=>setNight(!night));
async function load(){ready=false;$('loading').hidden=false;$('retry').hidden=true;try{kit=await fetch('/kit.json').then(r=>r.json());let loaded=0;const loader=new GLTFLoader();for(const a of kit.assets){if(!models.has(a.id)){const gltf=await loader.loadAsync(`/runtime/${a.id}.glb`);models.set(a.id,optimize(gltf.scene));}$('progress').textContent=`${++loaded} of ${kit.assets.length} models ready`;}parts=buildLayout(put,campus);for(const parent of [campus,...parts.levels,parts.terrace])instanceRepeated(parent);for(const a of kit.assets){const option=document.createElement('option');option.value=a.id;option.textContent=a.name;$('asset-select').append(option);}$('about-count').textContent=`All ${kit.assets.length}`;$('asset-count').textContent=`${kit.assets.length} models · ${placements.length} placements`;ready=true;$('loading').hidden=true;setView('campus',true);}catch(error){errors.push(error.message);$('progress').textContent='The campus kit is still being prepared. Retry when the exports are ready.';$('retry').hidden=false;}}
$('retry').addEventListener('click',load);load();
function tick(now){frameMs=frameMs*.9+(now-last)*.1;last=now;if(orbit.goal){const g=orbit.goal;orbit.target.lerp(g.target,.1);orbit.distance=THREE.MathUtils.lerp(orbit.distance,g.distance,.1);orbit.theta=THREE.MathUtils.lerp(orbit.theta,g.theta,.1);orbit.phi=THREE.MathUtils.lerp(orbit.phi,g.phi,.1);if(Math.abs(orbit.distance-g.distance)<.005&&orbit.target.distanceTo(g.target)<.005)orbit.goal=null;}updateCamera();renderer.render(scene,camera);requestAnimationFrame(tick);}requestAnimationFrame(tick);
window.__campus={secretScreen,ready:()=>ready,setView,selectAsset:showAsset,setNight,metrics:()=>({ready,secretFound,view:current,selected,loaded:[...models.keys()],used:[...new Set(placements.map(p=>p.id))],placements:placements.length,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,frameMs:Math.round(frameMs*10)/10,dpr:renderer.getPixelRatio(),errors:[...errors],camera:camera.position.toArray(),target:orbit.target.toArray(),cutaway:$('cutaway').checked,floor:Number($('floor').value),roofs:$('roofs').checked})};
