const fs=require('fs'),crypto=require('crypto');
for(const id of ['campus_tile_construction','campus_construction_decor']){
 const base='blender/environment/'+id+'/v01/',file=base+'validation/visual_review.json',r=JSON.parse(fs.readFileSync(file)),isTile=id==='campus_tile_construction';
 r.reviewedAt=new Date().toISOString();r.scope='model';
 r.checks.referenceFidelity={status:'passed',findings:isTile?'Shared radius-18 campus shell, trim and anchor interface preserved; earth interior makes this a distinct construction district. Quiet outer slate band remains continuous and level.':'Original campus-style scene follows requested landmarks: dominant open unfinished frame, tower crane, site office, coherent stocks and low barriers. The crane and open roof bays remain identifiable in silhouette.'};
 r.checks.construction={status:'passed',findings:isTile?'Close and reverse exported views show a continuous level deck and unbroken shell/trim. Earth texture fades inside the quiet band; no duplicate raised pads or route are authored into terrain.':'Revision 3 fixes the first-pass default cube UV selection by explicitly selecting Palette UVs. Close/reverse views show footing contact, lintels seated on columns, upper-floor support, attached crane mast/boom and deliberate hanging hook. Runtime geometry audit confirms empty route/landing and 2.642 m minimum edge clearance.'};
 r.checks.readability={status:'passed',findings:isTile?'Phone-width review shows a calm tan earth field inside a legible slate frame; subtle mineral variation does not become speckled noise.':'Phone-width review retains the yellow crane, white open building frame and blue office as three clear masses. Supplies and low barriers remain subordinate; open space separates the route.'};
 r.secondPass={status:'passed',findings:isTile?'Reassessed close/reverse/phone views after initial form/material check. Level interface and continuous trim remain clean from the opposite side; no repairs were needed.':'After source UV repair and guarded re-export, reassessed close/reverse/phone views plus rear/top/silhouette. Solid palette assignments are now consistent, roof bays remain open and crane connections read correctly. No further scoped construction defects found.'};
 r.evidence=r.evidence.filter(e=>['iso','rear','top'].includes(e.view));
 for(const v of ['iso','close','reverse','phone']){const p=base+'validation/inspector-'+v+'.png';r.evidence.push({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),view:'inspector-'+v});}
 r.userAcceptance={status:'pending',note:'No explicit user artistic acceptance yet.'};r.limitations=['In-campus combined composition is reviewed by the parent integration task.'];
 fs.writeFileSync(file,JSON.stringify(r,null,2)+'\n');
}
