const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const root=path.resolve(__dirname,'../../../..');const folder=path.relative(root,__dirname).replaceAll('\\','/');
const read=f=>JSON.parse(fs.readFileSync(path.join(__dirname,f),'utf8'));
const write=(f,x)=>fs.writeFileSync(path.join(__dirname,f),JSON.stringify(x,null,2)+'\n');
const m=read('asset.json'),report=read('validation/report.json'),r=read('validation/visual_review.json');
if(read('validation/inspector-state.json').entries[0].revision!==report.sha256)throw Error('Inspector hash is stale');
r.reviewedAt=new Date().toISOString();r.scope='model';
r.checks.referenceFidelity={status:'passed',findings:'Compared approved front and three-quarter concept with fixed front, left and isometric GLB views. Broad compact head, substantial twin pillars, bowed bridge, two cyan eyes, amber side cartridges and chalk lower rim retained. Continuous convex crown reconciles illustrative views; rear is the explicitly authorized small three-node panel.'};
r.checks.construction={status:'passed',findings:'Corrected shoulder front seating, replaced bridge cap with a curved subdivided solid and rounded boolean recesses, bevelled shoulder solids, added fitted chin. Close front/left/rear/underside show consistent mirrored cartridge seats, controlled seams and no floating mounts. Rear Y grooves meet under the amber nodes. Removed optional crown overlay after reverse view exposed its edge; continuous shell remains clean.'};
r.checks.readability={status:'passed',findings:'Inspected phone and small isometric views: cyan eyes, chalk shoulder outline and amber markers remain distinct. Rear panel stays subordinate. Desktop and touch showcase loading tests pass; canonical model has no clips and displays Rest.'};
r.checks.motion={status:'not_applicable',findings:'Model-only delivery; baseline animations await user authorization.'};
r.secondPass={status:'passed',findings:'Rechecked final export after bridge/shoulder/chin repairs and removal of the exposed crown overlay. Front symmetry, two-axis face curvature, left cartridge depth, rear panel and underside are clean in the final hash-matched Inspector capture. Some deliberate low-poly planes remain; generated profiles are illustrative rather than exact orthographic construction.'};
for(const view of ['iso','front','left','rear','bottom']){
 const p=folder+'/validation/close-'+view+'.png';r.evidence.push({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),view,mode:'shaded'});
}
for(const f of ['phone.png','small-silhouette.png']){const p=folder+'/validation/'+f;r.evidence.push({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex'),view:f,mode:'shaded'});}
r.userAcceptance={status:'pending',note:'User approved concept and model production; finished model artistic review remains pending.'};
r.limitations=['Illustrative spec PNGs precede production and retain unknown technical fields; verified delivery statistics are in the reference-pack README.','Baseline animations pending user authorization.'];
write('validation/visual_review.json',r);
m.animationHandoff={sha256:report.sha256,sourceHash:report.sourceHash,modelRevision:m.revision,status:'animation-pending',modelAcceptance:'pending',authorization:'Model production approved; animation authorization remains pending.',plannedClips:['idle','work','move','place','hit','resolve']};write('asset.json',m);
const pack='references/boundary_bridge_spec_pack_2026-09-30/';
fs.writeFileSync(path.join(__dirname,pack,'README.md'),`# Architect — Boundary Bridge\n\nApproved concept and illustrative model references, followed by the editable production model.\n\n- [Model spec sheet](architect-spec-sheet.png)\n- [Six-angle views](architect-six-angle-sheet.png)\n- [Anatomy and rear panel](architect-anatomy-sheet.png)\n- [Silhouettes and contours](architect-shape-study.png)\n- [Forehead bridge](architect-accessory-bridge.png)\n- [Service cartridges](architect-accessory-cartridges.png)\n\nThe images are concept references, not measured turnaround geometry. The anatomy bridge paragraph has a minor text overlap; its callout and accessory sheet remain legible. Production facts: revision ${m.revision}, ${report.triangles} triangles, ${report.materials} materials, ${report.meshes} runtime meshes, one embedded 32 × 4 palette image referenced through two texture bindings, no bones or clips. Grounded, metres, +Y up/+Z forward. Dimensions ${report.dimensions.map(x=>x.toFixed(3)).join(' × ')} m (W × H × D).\n\nFront landmarks: broad 3.35 m cartridge span, 2.139 m total height, crown/shoulder top, bridge centre 1.59 m, eye centres ±0.33 m at 0.84 m, cartridge centres ±1.40 m at 1.01 m. Rear panel 0.58 m square, three amber nodes in a Y relationship. Approximate uniform-scale comparison uses front/side/iso renders; no per-view stretching or claimed overlap score.\n\n[Source](../../copilot_architect_v01.blend) · [Technical report](../../validation/report.json) · [Author review](../../validation/visual_review.json)\n`);
fs.appendFileSync(path.join(__dirname,'decisions.md'),`\n## 2026-09-30 — Boundary Bridge production\nUser approved the stronger 02 Boundary Bridge concept and explicitly requested sheets followed by a polished model with a small rear detail. Six-sheet pack completed first; concealed rear interpretation adds a compact chalk-rimmed service panel and three amber nodes. Previous r39 recipe preserved. New model built from scratch with a continuous convex face and shell, seated chalk pillars, bowed solid forehead bridge with actual rounded recesses, amber cartridges and indigo chin. Model-only r${m.revision}: ${report.triangles}/4500 triangles, two materials and a packed 32×4 palette. Game showcase now binds the canonical Architect model, preserving existing gameplay stats. Author visual review and technical checks complete; user model acceptance and animations remain pending.\n`);
console.log(JSON.stringify({revision:m.revision,sha256:report.sha256,triangles:report.triangles}));
