import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import type { PerformanceReport } from '../../src/diagnostics/types';

test.describe('optional performance tracking', () => {
  test.setTimeout(120_000);

  test('records the showcase and actual encounter across in-app navigation', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await page.goto('/');
    await expect(page.getByTestId('home-screen')).toHaveAttribute('data-state', 'ready', { timeout: 90_000 });
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Campus settings' });
    await expect(settings.getByRole('link', { name: /Open stress test map/ })).toBeVisible();
    await settings.getByRole('checkbox', { name: /Performance tracking/ }).check();
    await settings.getByRole('button', { name: 'Done', exact: true }).click();
    const panel = page.getByTestId('performance-panel');
    const toggle = panel.getByRole('button', { name: 'Performance panel', exact: true });
    await toggle.click();
    await panel.getByLabel('Capture name').fill('Real game sources');
    await panel.getByRole('button', { name: 'Record', exact: true }).click();
    await toggle.click();
    await page.getByRole('button', { name: 'Inspect Towers' }).click();
    await expect(page.getByTestId('tower-showcase')).toHaveAttribute('data-state', 'ready', { timeout: 30_000 });
    await expect.poll(() => page.evaluate(() => window.__TOWER_PERFORMANCE__!.snapshot().streams.find(stream => stream.name === 'showcase')?.triangles?.p95 ?? 0)).toBeGreaterThan(0);
    await page.getByRole('button', { name: 'Back to Hub' }).click();
    await expect(page.locator('dialog.codex-dialog')).not.toBeVisible();
    await page.evaluate(() => { location.hash = '#/lab'; });
    await page.getByLabel('Advance automatically').uncheck();
    await page.getByRole('button', { name: 'Start encounter', exact: true }).click();
    for (let step = 0; step < 2; step++) await page.getByRole('button', { name: 'Step 60 ticks', exact: true }).click();
    await expect(page.getByTestId('encounter-tick')).toHaveText('120');
    await toggle.click();
    await panel.getByLabel('Measurement source').selectOption('encounter');
    await expect(panel).toContainText('Simulation CPU p95 / p99');
    await panel.getByRole('button', { name: 'Stop', exact: true }).click();
    const downloading = page.waitForEvent('download');
    await panel.getByRole('button', { name: 'Download report', exact: true }).click();
    const download = await downloading;
    const report = JSON.parse(await readFile((await download.path())!, 'utf8')) as PerformanceReport;
    expect(report.status).toBe('completed');
    expect(report.label).toBe('Real game sources');
    const showcase = report.streams.find(stream => stream.name === 'showcase')!;
    expect(showcase.triangles?.p95).toBeGreaterThan(0);
    expect(showcase.active).toBe(false);
    const encounter = report.streams.find(stream => stream.name === 'encounter')!;
    expect(encounter.kind).toBe('simulation'); expect(encounter.steps).toBe(120);
    expect(encounter.rawSamples.filter(sample => sample.reason === 'manual')).toHaveLength(2);
    expect(encounter.stageCpuMs.simulation).toBeDefined();
    expect(encounter.stageCpuMs.publication).toBeDefined();
    expect(errors).toEqual([]);
  });

  test('tracking is off by default, persists when enabled, and disables without blocking settings', async ({ page }, testInfo) => {
    await page.goto('/');
    await expect(page.getByTestId('home-screen')).toHaveAttribute('data-state', 'ready', { timeout: 90_000 });
    await expect(page.getByTestId('performance-panel')).toHaveCount(0);
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Campus settings' });
    const tracking = settings.getByRole('checkbox', { name: /Performance tracking/ });
    await expect(tracking).not.toBeChecked();
    await tracking.check();
    await expect(tracking).toBeChecked();
    await settings.getByRole('button', { name: 'Done', exact: true }).click();

    const panel = page.getByTestId('performance-panel');
    const toggle = panel.getByRole('button', { name: 'Performance panel', exact: true });
    await expect(toggle).toHaveAttribute('aria-expanded', 'false');
    await toggle.click();
    await expect(toggle).toHaveAttribute('aria-expanded', 'true');
    await expect(panel.getByLabel('Measurement source')).toBeEnabled();
    await expect(panel).toContainText('CPU submission p95 / p99');
    await expect(panel).toContainText('GPU time is not measured');
    await expect.poll(() => page.evaluate(() => window.__TOWER_PERFORMANCE__?.snapshot().streams.some(stream => stream.samples > 2))).toBe(true);
    await expect(panel).not.toContainText('Waiting for samples');
    const viewport = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, scrollWidth: document.documentElement.scrollWidth }));
    const bounds = await panel.boundingBox();
    expect(bounds).not.toBeNull();
    expect(bounds!.x).toBeGreaterThanOrEqual(0);
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width);
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(viewport.height);
    expect(viewport.scrollWidth).toBeLessThanOrEqual(viewport.width);
    await page.screenshot({ path: testInfo.outputPath('performance-panel.png'), fullPage: true });

    await page.reload();
    await expect(page.getByTestId('home-screen')).toHaveAttribute('data-state', 'ready', { timeout: 90_000 });
    await expect(page.getByTestId('performance-panel')).toBeVisible();
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await expect(settings.getByRole('checkbox', { name: /Performance tracking/ })).toBeChecked();
    await page.keyboard.press('Escape');
    await expect(settings).not.toBeVisible();
    await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeFocused();

    await toggle.click();
    await panel.getByRole('button', { name: 'Disable tracking', exact: true }).click();
    await expect(panel).toHaveCount(0);
    await expect.poll(() => page.evaluate(() => window.__TOWER_PERFORMANCE__ === undefined)).toBe(true);
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await expect(settings.getByRole('checkbox', { name: /Performance tracking/ })).not.toBeChecked();
  });

  test('reset preserves a recording and Stop keeps a downloadable final capture', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByTestId('home-screen')).toHaveAttribute('data-state', 'ready', { timeout: 90_000 });
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    const settings = page.getByRole('dialog', { name: 'Campus settings' });
    await settings.getByRole('checkbox', { name: /Performance tracking/ }).check();
    await settings.getByRole('button', { name: 'Done', exact: true }).click();

    const panel = page.getByTestId('performance-panel');
    await panel.getByRole('button', { name: 'Performance panel', exact: true }).click();
    await panel.getByLabel('Capture name').fill('UI recording test');
    await panel.getByRole('button', { name: 'Record', exact: true }).click();
    await expect(panel.getByRole('button', { name: 'Record', exact: true })).toBeDisabled();
    await expect(panel.getByRole('button', { name: 'Stop', exact: true })).toBeEnabled();
    await expect.poll(() => page.evaluate(() => window.__TOWER_PERFORMANCE__?.snapshot().streams.some(stream => stream.samples > 2))).toBe(true);
    await panel.getByRole('button', { name: 'Reset live window', exact: true }).click();
    const recording = await page.evaluate(() => window.__TOWER_PERFORMANCE__?.snapshot({ raw: true }));
    expect(recording?.status).toBe('recording');
    expect(recording?.label).toBe('UI recording test');
    expect(recording?.streams.some(stream => stream.rawSamples.length > 2)).toBe(true);
    await panel.getByRole('button', { name: 'Stop', exact: true }).click();
    await expect(panel.getByRole('button', { name: 'Stop', exact: true })).toBeDisabled();
    await expect(panel).toContainText('Manual capture: UI recording test · completed.');
    await panel.getByRole('button', { name: 'Reset live window', exact: true }).click();
    const pendingDownload = page.waitForEvent('download');
    await panel.getByRole('button', { name: 'Download report', exact: true }).click();
    const download = await pendingDownload;
    const data = await download.createReadStream();
    if (!data) throw new Error('The report download was unavailable.');
    const chunks: Buffer[] = [];
    for await (const chunk of data) chunks.push(Buffer.from(chunk));
    const report = JSON.parse(Buffer.concat(chunks).toString()) as { status: string; label: string; streams: { rawSamples: unknown[] }[] };
    expect(report.status).toBe('completed');
    expect(report.label).toBe('UI recording test');
    expect(report.streams.some(stream => stream.rawSamples.length > 2)).toBe(true);
  });
});
