import { expect, test } from '@playwright/test';
import { placeTower } from './mapActions';

test('tower stats tune one tower, validate drafts, reset, persist and lock during runs', async ({ page }, testInfo) => {
  await page.goto('/'); await page.getByLabel('Advance automatically').uncheck();
  await placeTower(page);
  const panel = page.locator('.tower-stats');
  await panel.locator('summary').click();
  const range = page.getByLabel('Tower range', { exact: true });
  const interval = page.getByLabel('Tower action interval (ms)', { exact: true });
  const work = page.getByLabel('Tower work per action', { exact: true });
  const damage = page.getByLabel('Tower damage per action', { exact: true });
  const commitment = page.getByLabel('Tower target commitment (ms)', { exact: true });
  const apply = page.getByRole('button', { name: 'Apply stats', exact: true });
  await expect(range).toHaveValue('5'); await expect(interval).toHaveValue('500');
  await interval.fill('1'); await expect(apply).toBeDisabled(); await expect(panel.getByRole('alert')).toBeVisible();
  await interval.fill('125'); await expect(page.getByTestId('stat-draft-timing')).toContainText('133.333 ms (8 ticks)');
  await work.fill('0.5'); await expect(apply).toBeDisabled();
  await work.fill('10'); await range.fill('8'); await damage.fill('0');
  await expect.poll(() => page.getByTestId('coverage-outline').evaluate((element: SVGGraphicsElement) => element.getBBox().width)).toBe(10);
  await commitment.fill('-1'); await expect(apply).toBeDisabled();
  await commitment.fill('200'); await apply.click();
  await expect(page.getByTestId('selected-tower')).toContainText('range 8');
  await expect.poll(() => page.getByTestId('coverage-outline').evaluate((element: SVGGraphicsElement) => element.getBBox().width)).toBe(16);
  await expect(interval).toHaveValue('133.333');
  await expect(page.getByTestId('tower-stat-rates')).toContainText('7.5 actions/s · 0 damage/s · 75 work/s');
  await expect(panel).toContainText('Base: 500 ms');
  await expect(page.getByTestId('tower-placement-stats')).toContainText('Cost: 30 Compute · footprint radius: 0.4 map units');
  await expect(page.getByTestId('compute')).toHaveText('270');
  await page.screenshot({ path: testInfo.outputPath('tower-stats.png'), fullPage: true });
  await placeTower(page, 4, 0); await panel.locator('summary').click();
  await expect(range).toHaveValue('5'); await expect(work).toHaveValue('5');
  await page.getByRole('button', { name: 'Tower 1', exact: true }).click(); await panel.locator('summary').click();
  await expect(range).toHaveValue('8');
  await page.getByRole('button', { name: 'Save locally', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Saved locally');
  await page.reload(); await page.getByRole('button', { name: 'Load save', exact: true }).click();
  await expect(page.getByTestId('placed-tower')).toHaveCount(2);
  await page.getByRole('button', { name: 'Tower 1', exact: true }).click(); await panel.locator('summary').click();
  await expect(range).toHaveValue('8'); await expect(work).toHaveValue('10');
  await page.getByRole('button', { name: 'Start encounter', exact: true }).click();
  await expect(range).toBeDisabled(); await expect(page.getByRole('button', { name: 'Reset stats', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Pause encounter', exact: true }).click(); await expect(interval).toBeDisabled();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Prepare same run again', exact: true }).click();
  await expect(page.getByTestId('encounter-phase')).toHaveText('Preparation');
  await page.getByRole('button', { name: 'Tower 1', exact: true }).click(); await panel.locator('summary').click();
  await expect(range).toHaveValue('8');
  await page.getByRole('button', { name: 'Reset stats', exact: true }).click();
  await expect(range).toHaveValue('5'); await expect(work).toHaveValue('5'); await expect(interval).toHaveValue('500');
  await expect(panel.locator('summary')).not.toContainText('custom');
  await expect.poll(() => page.getByTestId('coverage-outline').evaluate((element: SVGGraphicsElement) => element.getBBox().width)).toBe(10);
  await range.fill('0.0001'); await apply.click(); await expect(range).toHaveValue('0.0001');
  await page.getByRole('button', { name: 'Reset stats', exact: true }).click();
});
