import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const base='blender/towers/copilot_octocat_2_0/v01';
const folder='blender/towers/copilot_octocat_2_0_lowpoly/v01';
const m=JSON.parse(await fs.readFile(folder+'/asset.json'));
if(m.delivery)throw Error('Asset already delivered; initial setup must not overwrite it.');
const original=JSON.parse(await fs.readFile(base+'/asset.json'));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const bytes=await fs.readFile(original.source.path);
if(hash(bytes)!==original.delivery.sourceHash)throw Error('Original source hash changed');
await fs.copyFile(original.source.path,folder+'/references/octocat_2_0_r7.blend');
await fs.writeFile(folder+'/validation/original_baseline.json',JSON.stringify({source:original.source.path,sourceHash:hash(bytes),runtime:original.runtime,runtimeHash:hash(await fs.readFile(original.runtime))},null,2));
m.displayName='GitHub Octocat 2.0 Low Poly';
m.source.mode='procedural';m.source.recipe=folder+'/build.py';
m.budgets={triangles:4000,meshes:20,materials:2,textures:2,textureSize:512,bones:0};
m.contract=original.contract;m.texturePalettes=original.texturePalettes;m.exportSettings=original.exportSettings;
m.references=[{path:folder+'/references/octocat_2_0_r7.blend',provenance:'Pinned anatomy-corrected Octocat 2.0 revision 7 source; simplification input, hash '+original.delivery.sourceHash},...original.references.filter(r=>r.url)];
await fs.writeFile(folder+'/asset.json',JSON.stringify(m,null,2)+'\n');
await fs.writeFile(folder+'/decisions.md',`# GitHub Octocat 2.0 Low Poly\n\n## User direction — 2026-09-30\n\nCreate a separate low-poly version aiming for about 4,000 triangles. Hard delivery\nceiling: 4,000. Preserve the corrected revision 7 anatomy, palette, expression,\nwave pose and accessory anchors. The original model remains unchanged.\n\n## Reference priorities and landmarks\n\nPinned original source owns identity and proportion; the GitHub Animation Team\nturnaround and construction sheets published at https://www.tonytimetables.com/mona/\nown anatomy. Exactly five tentacles meet beneath the head: two act as arms, three\nsupport this upright pose. Preserve bulbous tips, flatter inner faces, five cups\nper tentacle, two pointed inset ears, shallow forehead dip, broad cheek lobes,\nopen smile and four whiskers. Compare front, side, reverse/underside and isometric\nnegative spaces against the original before handoff.\n\n## Construction\n\nUse region-specific topology reduction of the pinned editable sculpt, giving the\nhead silhouette and body most of the budget. Refit facial surfaces to the reduced\nhead and cups to the reduced skin. Keep original 40 x 4 palette and 512 x 512 face\nmap packed/embedded. Preserve authored scale, placement root and nine anchors.\nSmooth normals on deliberate low-density planes retain the friendly rounded look.\nThe shared pipeline owns export; the recipe only saves a staged Blender source.\n\n## Animation handoff\n\nStatic model milestone; animation pending. No placeholder clips. Future baseline:\nidle, work, move, place, hit, resolve, with three-support rest anatomy and shared\ntower digital assembly/disintegration effects. User acceptance is separate from\nauthor review and remains pending.\n`);
console.log('Prepared pinned source, contract and brief');
