import {readFile,writeFile} from 'node:fs/promises';
const plan=JSON.parse(await readFile('tools/github-campus-kit/plan.json','utf8'));
const colors={stucco:'#CAD1CE',trim:'#E2EDF0',stone:'#89A4B8',iron:'#232925',wood:'#A77B55',oak:'#CFAC77',orange:'#D86C35',orange_light:'#F19A50',slate:'#48647D',teal:'#82DADD',green:'#0FBF3E',cream:'#F2E3C9'};
const descriptions={
 gh_warehouse:'Three-story, 30 × 18 m interpreted warehouse shell with 5 m level intervals and a 15.24 m historical height cue. Ninety-four true arched window openings, light stucco, recessed thin glazing, deep sills, full-thickness arch intrados, horizontal bands, upper cornice and corner pilasters. Empty interior; no floor slabs or full roof. Ground-floor front central two bays are an entrance opening. Per-level front, back and combined sides form removable groups.',
 gh_atrium:'14 m square, 10 m high interpreted glass atrium with pale slender-but-readable mullions, charcoal perimeter frames, open central entrance, stepped oak-topped seating and timber-framed transparent skylight. Public IA atrium photographs govern the spatial vocabulary; this is a new detached campus interpretation, not their measured project.',
 gh_container:'6 × 3 m orange collaboration container, open front with actual corrugated side and back profiles, hollow corner-post construction expressed by broad posts/caps, contrasting top/bottom rails, wood floor, real rear window cutouts and removable ribbed roof. Furniture belongs to separate props. Standardized size is an authored interface, not a recovered GitHub container measurement.',
 gh_facade_bay:'Reusable 3 × 5 m warehouse facade bay with one real arched recess, 0.45 m wall thickness, 0.91 m arch radius, pale voussoir trim, deep sill and thin charcoal mullions. No flat painted arch or solid wall behind glazing.',
 gh_entry_portal:'5 m wide interpreted front portal: pale projecting canopy, slender steel diagonal supports, paired transparent doors and charcoal fitting frame. Small green canopy edge introduces the current brand family. Portal has no opaque wall blocking its doorway; model does not invent an official logo.',
 gh_glass_partition:'6 × 3.6 m office partition with a central paired glazed door, slim charcoal metal frame, broad pale privacy bands and fitted wood handles. Transparency is deliberate and readable rather than photoreal refraction.',
 gh_roof_terrace:'30 × 18 m rooftop deck with individual broad oak boards, steel perimeter posts and two rails, warm wood handrail, and an 8 × 5 m open timber pergola. Deck top is Y=.25; guardrail top Y=1.25; pergola top Y=3.8. Roof furniture is separate. Roof group controls overhead pergola slats.',
 gh_bridge:'8 m X-span, 3 m depth, 3.5 m high campus connector with charcoal deck structure, oak plank walking surface, metal posts, cable-like broad rails, clear guard panels and pale timber-supported cover. Root is at deck underside Y=0; use at elevated floor levels. Coverage is an interpreted campus link, not a claim about real GitHub site adjacency.'
};
for(const asset of plan.assets.filter(a=>a.owner==='architecture')){
 const folder=`blender/environment/${asset.id}/v01`, file=`${folder}/asset.json`, m=JSON.parse(await readFile(file,'utf8'));
 if(m.delivery){console.log(`${asset.id}: already delivered; preserve source contract and decisions`);continue;}
 m.palette={storage:'texture',colors};m.texturePalettes=[{material:'github_architecture_palette',size:[64,4],roles:Object.fromEntries(Object.entries(colors).map(([role,color],i)=>[role,{color,rect:[i*4,0,4,4]}]))}];m.exportSettings={...(m.exportSettings||{}),paletteSampler:'linear'};
 m.budgets={triangles:50000,meshes:40,materials:2,textures:1,textureSize:64,bones:0};
 m.overrides=asset.id==='gh_roof_terrace'?[]:[{field:'material.transparency',material:'clear_architectural_glazing',reason:'Thin transparent glazing deliberately allows furnished interior visibility and is isolated from the opaque single-atlas structure. No refraction or layered decals.'}];
 await writeFile(file,JSON.stringify(m,null,2)+'\n');
 await writeFile(`${folder}/build.py`,`"""${asset.name}. Original editable procedural source."""\nimport sys\nfrom pathlib import Path\nfolder=Path(__file__).resolve().parent\nsys.path.insert(0,str(folder.parents[3]/'tools'/'github-campus-kit'))\nfrom architecture_tools import build\nbuild('${asset.id}',folder)\n`);
 await writeFile(`${folder}/decisions.md`, `# ${asset.name}\n\n## User direction and scope\n\nUser authorized a reusable 3D GitHub office/campus kit plus disposable prototype on 2026-09-30. This source is an original friendly low-poly interpretation, not a measured as-built reconstruction. Editable Blender remains authoritative and all geometry uses metres, Y up, +Z front. No third-party photograph is used as runtime texture.\n\n## Reference priorities and primary form\n\n${descriptions[asset.id]}\n\nPublic references: [original architect](https://fm-arch.com/workitems/github/), [historic entrance photograph and documentation](../../../../docs/research/github-offices-2026-09-30/report.html), [contemporary atrium](https://interiorarchitects.com/projects/githubatrium/) and [roof concrete furniture context](https://concreteworks.com/projects/github-hq/). The dated research report, source registry and photographs remain the provenance record. Examined contact-exterior, contact-original-architect and contact-atrium sheets before construction. The historical 15.24 m height is a verified cue; footprint, floor intervals, openings and campus connections are authored interfaces.\n\n## Construction and materials\n\nPrimary outline resolved from the documented warehouse/atrium/container vocabulary before trim. Arches use extruded profile surfaces, real voids and full-depth intrados; borders are radial continuous profiles, not crossed beveled bars. Repeated windows share centers, springlines and sill heights. Boards, posts, frame rails and glazing have distinct seats and thickness. A 64 × 4 packed sRGB palette supplies the opaque structure; role UVs sample padded swatch centers. Glass is a practical alpha exception needed for furnished interior views; no refraction, no fake opaque backing. Static environment architecture requires no skeleton or invented clips.\n\n## Review\n\nTechnical validation and hash-bound author review live under validation/. User artistic acceptance remains pending. Canonical source is preserved by guarded delivery.\n`);
}
