// Filled only after the author inspected current registered GLB screenshots.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
// This archival assessment cannot certify an uninspected later model revision.
const reviewedExports={gh_warehouse:'b8994233f65bbdeb029f5d0d2fd8f46a2f95ef2caac70bf2f441c0dffabe4903',gh_atrium:'bfcd0c41bdbf62b30c0805ee6d66fc667c378634e236f868091a78d5d1806ef3',gh_container:'85ff88faf663c740128d210edeca6a7f6df96e91345262f1a593404adada644c',gh_facade_bay:'1a46797a9e4ece7a5fff9d9e89d9fd3e42714ac2a106a54a6862c21766f36a33',gh_entry_portal:'40c27c606ef4ee23c215251267d7b6b4cd8f4c89aea504b2f1a3d5a03a2252e1',gh_glass_partition:'b52eb713988d322ab0840fdb6acd1cd69b513e336ec3e4b6c87d26185f97e2d0',gh_roof_terrace:'ac2ea2fcd09515e650bcccd82538858329baa89c54c69bd1a1ab45cbc9930824',gh_bridge:'b8a2e8947dec0bf2d94ac06fd117c508ac360d9897938d5e62f922e0c7f4ef72'};
const assessments={
 gh_warehouse:{views:['iso','side','top','phone'],reference:'Three-story light stucco and a 15.24 m height cue read as a warehouse, with real arched recesses, deep pale sills, slim iron mullions and horizontal bands. The researched facade vocabulary is preserved; spacing and footprint are explicitly authored, not a measured reconstruction.',construction:'Replaced overlapping corner bands with front/back continuations and fitted butt-ended side bands; repeated cornice corners now read consistently. Upper east bridge opening has actual full-depth clearance rather than a painted doorway. The shell is hollow and intentionally has no floors or roof; three levels have separate removable walls.',readability:'At the 390 px Inspector viewport the three levels, arches and central entrance remain clear; roofless silhouette reads as a shell and needs the separate deck module in the campus.',second:'Inspected the rebuilt isometric, east elevation, top and current phone export after repairing corner joins and adding the upper doorway. No remaining irregular arch rhythm or wall behind the upper opening was observed.'},
 gh_atrium:{views:['iso','west_access','phone'],reference:'Pale glazing grid, exposed timber skylight beams and stepped oak-topped seating translate the public contemporary GitHub atrium vocabulary into an original detached campus volume. The suspended contribution artwork is intentionally a separate model.',construction:'Thin low-alpha glazing is isolated from one opaque packed palette. Added a receiving gallery and actual 25-tread narrow west stair, with an upper doorway and clipped mullion/glass sections. Gallery deck Y5.30 matches the covered bridge when placed atY5; stair and landing rails are fitted and the rear seating stays clear.',readability:'Current 390 px viewport clearly separates glazing, roof grid, stairs and stepped seating. Clear glass allows the contribution artwork and furniture to remain visible without dense refraction.',second:'Rechecked current exported west elevation, isometric and phone after replacing the empty upper connection with a real stair/gallery and lowering the gallery to match the bridge. The doorway is clear; opposite glazing can be seen through it and is not an opaque local backing.'},
 gh_container:{views:['iso','front','rear','phone'],reference:'The orange corrugated collaboration container, broad corner posts, black caps and wood floor preserve the distinctive original GitHub office motif. The 6 m module size is authored; this is not a recovered historic container measurement.',construction:'Replaced solid window backing with fitted perimeter frames, retained actual rear wall cutouts and repaired a 2 cm bottom-panel seam visible from the rear. Corrugation ribs stop at windows and continue above/below. Front is a true open collaboration portal; removable roof has fitted raised ribs.',readability:'Orange silhouette, broad corrugation and corner caps remain clear at phone width; the empty studio is ready for independent furnishings.',second:'Viewed current front/rear/oblique and phone renders after repairing the rear windows and panel seam. The wall is continuous around both window voids, and no opaque backing or bright crack remains.'},
 gh_facade_bay:{views:['iso','front','rear','phone'],reference:'The arch springline, narrow metal muntins, light projecting sill and broad stucco spandrel reproduce the researched historic warehouse vocabulary at modular scale.',construction:'A coherent twelve-segment extruded arch and full-depth opening replace flat painted treatment. Widened base/cornice endcaps slightly so their visible ends are not coincident with the stucco end plane; front and reverse reveal the actual aperture.',readability:'Single tall arched window and chunky pale trim remain recognizable on the 390 px viewport; repeated deployment gives a clear facade rhythm.',second:'Inspected the current rebuilt front, rear, oblique and phone after endcap repair. The side-end band shimmer is removed, the sill has deliberate depth and the arch frame remains concentric.'},
 gh_entry_portal:{views:['iso','front','rear','phone'],reference:'Light projecting canopy, charcoal paired doors and slim steel supports follow the documented warehouse entrance language; the green edge is a current GitHub palette interpretation, not a historical measured paint claim.',construction:'Portal has clear glass and no solid opaque wall behind its door. Paired handles sit on the glazed leaves; diagonal brackets connect canopy to portal frame. The rear view confirms the thin doorway construction.',readability:'Canopy, broad contrasting jambs, handles and restrained green line remain clear at phone width.',second:'Rechecked front, rear, oblique and phone with the entrance reference visible. No floating handle, blocking wall, crossed canopy connection or inconsistent symmetry was observed; dimensions remain an authored interface.'},
 gh_glass_partition:{views:['iso','front','rear','phone'],reference:'The charcoal framed glass partitions and paired doors translate photographed office meeting-room fronts with broad pale privacy bands instead of tiny decals.',construction:'Main vertical frame members now terminate between top/bottom rails instead of overlapping their outer end faces. Central paired-door mullion was extended to meet the transom and leaf panes fitted to the resulting aperture. Handles have deliberate depth and clear frames.',readability:'Pale bands and wood handles make the glazed doors recognizable at phone width; charcoal frames rely on the light wood/stucco interior context and appear lower contrast against the Inspector dark background.',second:'Rechecked current rebuilt front/rear/oblique and phone after frame-junction repair. Central mullion no longer floats below the top rail; only fitted corner feet project and the privacy bands align.'},
 gh_roof_terrace:{views:['iso','rear','top','phone'],reference:'Broad oak deck boards, industrial rails and an open timber pavilion use the researched GitHub rooftop terrace vocabulary. Furniture is separate; pergola footprint and complete deck layout are authored.',construction:'Deck slab and all intersecting wood boards are cut around the fixed stair interface X[11.1,14.1],Z[-5.5,1.25]. Guards follow the two sides and bottom edge while the upper landing stays open. Small intermediate oak step keeps roof access rises under .3 m.',readability:'At phone width the perimeter, pergola and rectangular stair aperture are visible. Large usable deck intentionally leaves space for the separate concrete seating/planters.',second:'Reviewed current top, rear, isometric and phone after cutting the roof aperture. Top view confirms no floor backing in the stairwell; side/bottom guards and open arrival edge form a coherent access point.'},
 gh_bridge:{views:['iso','front','rear','phone'],reference:'The bridge is a new campus connector in the same timber/iron/pale architecture family, rather than a claim about real GitHub site adjacency.',construction:'Deck has broad individual boards, fixed iron posts, warm wood handrails, clear guards and a timber-supported pale cover. Symmetric rails terminate at structural posts; posts express their small exposed top caps. End openings remain usable.',readability:'Covered linear span and warm walking surface remain clear on the 390 px viewport. Thin rails are subordinate to the primary deck/roof silhouette.',second:'Rechecked front/rear/oblique and phone after confirming the receiving warehouse and atrium interfaces. No blocking end panel or detached guard was observed; bridge top deck Y=.30 aligns with atrium landing at5.30 when placed atY5.'}
};
for(const [id,a] of Object.entries(assessments)){
 const folder=`blender/environment/${id}/v01`,file=`${folder}/validation/visual_review.json`,r=JSON.parse(await readFile(file,'utf8'));
 if(r.sha256!==reviewedExports[id])throw Error(`${id}: later export needs a new personal visual assessment, not this archived review.`);
 r.scope='model';r.reviewedAt=new Date().toISOString();r.checks={referenceFidelity:{status:'passed',findings:a.reference},construction:{status:'passed',findings:a.construction},readability:{status:'passed',findings:a.readability},motion:{status:'not_applicable',findings:'Deliberately static environment architecture, no skeleton or authored clips.'}};
 r.secondPass={status:'passed',findings:a.second};r.userAcceptance={status:'pending',note:'User authorized creation but has not explicitly accepted this model revision.'};
 r.limitations=['Original interpreted campus architecture; complete measured GitHub as-built CAD documentation was not found.'];if(id==='gh_glass_partition')r.limitations.push('Dark frames need a light interior background for strongest contrast; the pale bands and handles remain legible on the dark Inspector background.');
 r.evidence=await Promise.all(a.views.map(async view=>{const path=`${folder}/validation/${view}.png`,bytes=await readFile(path);return {path,sha256:createHash('sha256').update(bytes).digest('hex'),view,mode:'shaded'};}));
 await writeFile(file,JSON.stringify(r,null,2)+'\n');
 const decision=await readFile(`${folder}/decisions.md`,'utf8');
 await writeFile(`${folder}/decisions.md`,decision+`\n## Author review — revision ${r.revision}\n\n${a.construction}\n\n${a.second}\n\nActual current registered GLB rendered in the shared Inspector; authored source and export hashes are bound in validation/visual_review.json. Artistic user acceptance remains pending.\n`);
}
