import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import {findAsset,hash} from '../asset-pipeline/contracts.mjs';
import {reviewAsset} from '../asset-pipeline/visual-review.mjs';
const plan=JSON.parse(await readFile('tools/github-campus-kit/plan.json','utf8'));
const sourceRegistry=JSON.parse(await readFile('docs/research/github-offices-2026-09-30/sources.json','utf8'));
const sourcesByAsset={gh_warehouse:['S01','S02','S17'],gh_atrium:['S14'],gh_container:['S01','S03','S06'],gh_facade_bay:['S17'],gh_entry_portal:['S17','S28'],gh_glass_partition:['S01'],gh_roof_terrace:['S02','S05'],gh_bridge:['S01'],gh_workstation:['S04'],gh_meeting_set:['S04'],gh_library:['S10','S11'],gh_cafe_bar:['S01'],gh_lounge:['S10','S12'],gh_pendant:['S01'],gh_thinktocat:['S15','S16'],gh_sign:['S28'],gh_contribution_art:['S14','S29'],gh_roof_furniture:['S05'],gh_floor_wood:['S01'],gh_floor_paving:[],gh_floor_hex:['S01'],gh_timber_frame:['S01','S02'],gh_stairs:['S03'],gh_planter:['S05'],gh_tree:[],gh_courtyard:['S05','S29'],gh_membrane_wall:['S10','S11','S13'],gh_ceiling_services:['S01'],gh_indoor_park:['S01','S06']};
Object.assign(sourcesByAsset,{gh_bookshelf_pod:['S01','S06'],gh_worklounge_pod:['S01','S06'],gh_recessed_lounge:['S01','S06'],gh_secret_octocat:['S16'],gh_mural_universe:['S36'],gh_mural_currents:['S36'],gh_mural_collaboration:['S36','S27']});
const kit={schemaVersion:1,id:'github_campus',version:'v01',createdAt:new Date().toISOString(),style:plan.intent,units:'metres',runtimeAxes:{up:'+Y',front:'+Z'},blenderAxes:{up:'+Z',front:'-Y'},scope:'Static environment art. Campus interpretation; not an as-built survey or collision simulation.',research:'docs/research/github-offices-2026-09-30/report.html',prototype:'prototypes/github-campus/',assets:[]};
for(const asset of plan.assets){
 const item=await findAsset(asset.id,'v01'),m=item.data,review=await reviewAsset(item);if(!review.ready)throw Error('Incomplete current review '+JSON.stringify(review));
 const report=JSON.parse(await readFile(m.delivery.report,'utf8'));
 const bytes=await readFile(m.runtime);if(hash(bytes)!==m.delivery.sha256)throw Error('Changed runtime '+m.id);
 kit.assets.push({id:m.id,name:m.displayName,group:asset.owner==='architecture'?'Architecture':asset.owner==='props'?'Furniture and identity':'Floors, structure and site',version:m.version,revision:m.revision,source:m.source.path,runtime:m.runtime,manifest:item.manifest,recipe:m.source.recipe,decisions:m.decisions,dimensions:report.dimensions.map(v=>Math.round(v*1000)/1000),triangles:report.triangles,meshes:report.meshes,materials:report.materials,textures:report.textures,bytes:bytes.length,sha256:m.delivery.sha256,sourceHash:m.delivery.sourceHash,anchors:m.contract.anchors,review:review.file,preview:item.manifest.replace('/asset.json','/validation/iso.png'),sources:(sourcesByAsset[m.id]||[]).map(id=>sourceRegistry.sources.find(s=>s.id===id)).filter(Boolean).map(s=>({id:s.id,title:s.title,url:s.url})),inferred:'Footprint, room layouts and furniture scale are authored. Historical warehouse height uses published50ft datum; membrane wall thickness uses documented1ft assembly.'});
}
kit.totals={models:kit.assets.length,triangles:kit.assets.reduce((n,a)=>n+a.triangles,0),runtimeBytes:kit.assets.reduce((n,a)=>n+a.bytes,0),editableSourceBytes:(await Promise.all(kit.assets.map(async a=>(await stat(a.source)).size))).reduce((a,b)=>a+b,0)};
await mkdir('assets/kits',{recursive:true});await writeFile('assets/kits/github-campus-v01.json',JSON.stringify(kit,null,2)+'\n');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const cards=kit.assets.map(a=>`<article data-search="${esc(a.name+' '+a.id+' '+a.group).toLowerCase()}"><a href="http://127.0.0.1:4174/?asset=${a.id}&version=v01"><img loading="lazy" src="../../${a.preview}" alt="${esc(a.name)} model"></a><p class="tag">${a.group}</p><h2>${esc(a.name)}</h2><p class="id">${a.id} · v01 / revision${a.revision}</p><p>${a.dimensions.map(n=>n.toFixed(2)).join(' × ')} m · ${a.triangles.toLocaleString()} triangles</p><div class="actions"><a href="../../${a.runtime}">GLB model</a><a href="../../${a.source}">Blender source</a><a href="../../${a.manifest}">Contract</a></div><p class="sources">${a.sources.length?a.sources.map(s=>`<a href="${esc(s.url)}">${esc(s.title)}</a>`).join(' · '):'Original campus landscape addition'}</p></article>`).join('');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GitHub campus model kit</title><style>:root{font-family:system-ui,sans-serif;color:#232925;background:#F2F5F3}body{margin:0}header,main{max-width:1240px;margin:auto;padding:30px}header{padding-top:48px}h1{font-size:42px;letter-spacing:-1.5px;margin:12px0}h2{font-size:18px;margin:6px0}p{line-height:1.6}.eyebrow,.tag{color:#167c37;font-size:11px;text-transform:uppercase;letter-spacing:1px}header p{max-width:850px}.toplinks,.actions{display:flex;flex-wrap:wrap;gap:12px}a{color:#167c37}input{width:100%;padding:14px;font:inherit;box-sizing:border-box;border:1px solid #B6BFB8;border-radius:6px;margin:10px0 24px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}article{background:white;border:1px solid#E4EBE6;border-radius:9px;overflow:hidden;padding:16px}article img{display:block;width:calc(100% + 32px);margin:-16px -16px 16px;aspect-ratio:1.2;object-fit:cover}article p{font-size:12px}article .id{color:#909692;font-size:11px}.sources{font-size:10px!important}.actions a{font-size:12px;font-weight:600}[hidden]{display:none!important}.note{background:#E4EBE6;padding:20px;border-radius:6px}@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:550px){.grid{grid-template-columns:1fr}header,main{padding:20px}h1{font-size:32px}}</style><header><span class="eyebrow">Reusable environment art · v01</span><h1>GitHub campus kit</h1><p>${kit.assets.length} editable models bring together the warm warehouse, orange container studios, pale oak reading niches, luminous meeting walls, rooftop concrete furniture contribution-green artwork, bookshelf work lounges and authored mural panels informed by the research.</p><div class="toplinks"><a href="http://127.0.0.1:5199/">Open campus prototype</a><a href="../research/github-offices-2026-09-30/report.html">Research and photographs</a><a href="../../assets/kits/github-campus-v01.json">Detailed inventory</a><a href="../../exports/github-campus-v01.zip">Download complete pack</a></div><p class="note">This is an original low-poly interpretation of several GitHub office design phases. It is not a measured replica. Assets are static and use embedded palette textures. GLB axes are Y up / Z front; Blender sources use Z up / minus-Y front. Furniture ensembles remain editable meshes in Blender. The prototype provides camera exploration, not a collision-based walk simulation.</p></header><main><label for="search">Find a model</label><input id="search" type="search" placeholder="Building, roof, library, floor, tree…"><div class="grid">${cards}</div></main><script>document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('article').forEach(a=>a.hidden=!a.dataset.search.includes(q))})</script></html>`;
await writeFile('docs/design/GitHub_Campus_Kit.html',html.replaceAll('margin:12px0','margin:12px 0').replaceAll('margin:6px0','margin:6px 0').replaceAll('margin:10px0','margin:10px 0'));
await writeFile('artifacts/github-campus/kit-verification.json',JSON.stringify({passed:true,checkedAt:new Date().toISOString(),totals:kit.totals,assets:kit.assets.map(a=>({id:a.id,revision:a.revision,sha256:a.sha256,sourceHash:a.sourceHash,authorReview:'ready',userAcceptance:'pending'}))},null,2)+'\n');
console.log(JSON.stringify({passed:true,...kit.totals}));
