const fs=require('node:fs');const path=require('node:path');
const palette={wood:'#BF9465',wood_dark:'#835739',mahogany:'#77483B',dark:'#232925',paper:'#F2F5F3',slate:'#89A4B8',screen:'#153F50',green:'#0FBF3E',leaf:'#70B5B4',gold:'#E9B864',purple:'#8534F3',blue:'#5579B8',bordeaux:'#7C354D',stone:'#D2D0C5',bronze:'#98794C',bronze_dark:'#65583C'};
const ids=JSON.parse(fs.readFileSync('tools/github-campus-kit/plan.json')).assets.filter(a=>a.owner==='props');
const briefs={
gh_workstation:['furniture-01.jpg','original-architect-09.jpg','Broad oak butcherblock surface, iron rectangular trestles, chunky blue chair, forward monitor and open laptop. Code marks deliberately enlarged for close virtual-office tours.'],
gh_meeting_set:['furniture-05.jpg','rapt-expansion-01.jpg','Mahogany slab above two broad trestles, eight upholstered burgundy chairs. Actual table furniture proportions inferred; ensemble is a reusable contemporary office interpretation.'],
gh_library:['rapt-expansion-02.jpg','rapt-expansion-01.jpg','Pale wood sit-in shelving: central true arch negative space, side reading bays and upper open shelves. Burgundy folded carrel screens in front capture the expansion identity.'],
gh_cafe_bar:['original-architect-05.jpg','original-architect-17.jpg','Long oak bar and wood panelled front, four iron stools, light rear wall with bottle shelves and espresso machine; strong horizontal counter landmark.'],
gh_lounge:['expansion-contractor-08.jpg','original-architect-11.jpg','Soft blue and purple upholstery with broad rolled-look arms, visible cushion rhythm, stump coffee table. Distinct room-scale color accents.'],
gh_pendant:['original-architect-03.jpg','original-architect-15.jpg','Three hanging warehouse lamps, distinct black shades and visible warm bulbs/cables. Origin at lowest bulb; raise asset to selected ceiling height.'],
gh_thinktocat:['thinktocat-03.jpg','thinktocat-01.jpg','Original low-poly interpretation of Tony Jaramillo Thinktocat: big round head, two cat ears, lowered thoughtful face, chin supported by curled tentacle, crossed elbow tentacle, two seated feet, swept rear tail, white tapered plinth. Bronze palette keeps sculptural identity. No existing character asset was edited.'],
gh_sign:['exterior-01.webp','report.html','Official current white GitHub lockup sampled directly from downloaded vector outlines, preserving relative proportions and negative spaces; independently authored graphite monument slab. Branding is source reference and remains GitHub property.'],
gh_contribution_art:['atrium-01.jpg','atrium-03.jpg','Static suspended green contribution plates in a 23 by 17 lattice with uneven depth and cat negative-space motif. The source installation resolves Mona from a particular angle; this modular interpretation resolves a cat motif from front and becomes abstract from oblique views. Opaque plates intentionally simplify polycarbonate at phone scale; no unsupported moving mechanism.'],
gh_roof_furniture:['roof-furniture-04.jpg','roof-furniture-01.jpg','Concrete round pedestal chess table and inset board, two timber/concrete benches, rear integrated concrete planter. Roof furniture proportions inferred from photographs.']};
for(const a of ids){
 const folder=`blender/environment/${a.id}/v01`;const file=`${folder}/asset.json`;const manifest=JSON.parse(fs.readFileSync(file));
 fs.copyFileSync('blender/environment/story_courtyard/v01/model_tools.py',`${folder}/props_tools.py`);fs.copyFileSync('tools/github-campus-kit/props_models.py',`${folder}/props_models.py`);
 fs.writeFileSync(`${folder}/build.py`,`from pathlib import Path\nimport sys\nfolder=Path(__file__).resolve().parent\nsys.path.insert(0,str(folder))\nfrom props_models import build\nbuild('${a.id}',folder)\n`);
 manifest.palette={storage:'texture',colors:palette};manifest.texturePalettes=[{material:a.id+'_palette',size:[64,4],roles:Object.fromEntries(Object.entries(palette).map(([role,color],i)=>[role,{color,rect:[i*4,0,4,4]}]))}];
 manifest.budgets={triangles:30000,meshes:4,materials:1,textures:1,textureSize:64,bones:0};manifest.exportSettings={paletteSampler:'linear'};
 manifest.contract.grounded=true;manifest.contract.groundY=0;manifest.contract.groundTolerance=.004;
 manifest.references.push(...briefs[a.id].slice(0,2).map(name=>({path:'docs/research/github-offices-2026-09-30/'+(name==='report.html'?'':'images/')+name,provenance:'Public photo reference from research image-index.json; not used as a runtime texture.'})));
 if(a.id==='gh_sign')manifest.references.push({path:`${folder}/references/official/GitHub Logos/SVG/GitHub_Lockup_White.svg`,provenance:'Unmodified vector from https://brand.github.com/GitHub_Logos.zip accessed 2026-09-30. GitHub trademarks and artwork remain GitHub property. Used for this private office interpretation, not a new project logo.'});
 fs.writeFileSync(file,JSON.stringify(manifest,null,2)+'\n');
 fs.writeFileSync(`${folder}/decisions.md`,`# ${a.name}\n\nUser direction, 2026-09-30: create reusable GitHub office/campus models and a disposable assembled prototype.\n\n## Reference and primary form\n\n${briefs[a.id][2]}\n\nResearch references: ${briefs[a.id].slice(0,2).join(', ')}. Exact as-built office measurements are unavailable; this is an original friendly low-poly interpretation. The requested target size is approximately ${a.size.join(' × ')} metres in X/Y/Z; furniture ensembles may have slight practical variation. Resolve broad body silhouette, repeated rhythm and real negative spaces before fittings.\n\n## Interfaces and delivery\n\nCenter X/Z; floor contact Y=0; front+Z. Static environment, no rig or invented clips. All component transforms joined/applied beneath root. One 64×4 packed palette texture with deliberate padded swatches, no photo textures. Opaque plate treatment is an intentional readability/performance interpretation for suspended contribution art. Author review and technical validation are separate; explicit user acceptance remains pending.\n`);
}
console.log('Installed recipes and manifest briefs for '+ids.length+' office props.');
