import fs from 'node:fs/promises';
const palette={oak:'#BF9465',oak_edge:'#9C744C',grain:'#C8A274',walnut:'#835739',ivory:'#E5DBC4',fabric:'#A69A86',dark:'#232925',brick:'#A56548',mortar:'#C9B69C',gold:'#E9B864',green:'#70B5B4',blue:'#5579B8',bordeaux:'#7C354D',purple:'#8534F3',paper:'#F2F5F3',red:'#B84035'};
const assets=[{id:'gh_bookshelf_pod',name:'Bookshelf and side reading nook',size:[1.6,3.2,2.2],reference:'40d0e8b0-9bc0-4c5e-b6f4-ce4747ce5a28',brief:'Narrow floor-to-ceiling oak bookshelf end-cap with five shelf levels, dense varied book spines, a small sculptural bust niche and an oak circular disk in a warm halo above. On the negative-X side a genuinely cut rounded rectangular opening reveals a full-depth cushion, padded diamond upholstery and a black reading lamp. Primary landmarks: 1.6m-wide front face, 2.2m-deep cabinet, 3.2m height, side portal 1.50m wide and 1.92m high, large circular halo centered at 2.77m.'},{id:'gh_worklounge_pod',name:'Wide oak window reading lounge',size:[6,3.2,2.4],reference:'17f6b711-ab94-407c-824b-147fa3180491',brief:'Broad horizontal 4.78 × 2.19m rounded rectangular real opening through a 6m-wide oak front, with .25m corner radii and a full-depth enclosure. Brick wall remains visible behind three long seating cushions, cream padded inner edges/side lining and a reading lamp. The front is deliberately horizontal, without the arch used by the earlier library ensemble.'},{id:'gh_recessed_lounge',name:'Raised platform recessed work lounge',size:[4.5,3.2,2.4],reference:'e36e3dfd-1061-4ed1-b033-bb486e10d32c',brief:'Dark wide rectangular framed work nook with a raised oak platform, broad warm brown couch, separate loose pillows, striped draped throw and tassels, tiny crossed-leg folding table, cup, laptop and red lantern. Rear warehouse timber remains visible; under-step glow is restrained source-authored emission.'}];
for(const a of assets){
 const folder=`blender/environment/${a.id}/v01`,file=folder+'/asset.json',m=JSON.parse(await fs.readFile(file,'utf8'));
 for(const name of ['pod_tools.py','pod_models.py'])await fs.copyFile('tools/github-campus-kit/'+name,folder+'/'+name);
 await fs.writeFile(folder+'/build.py',`from pathlib import Path\nimport sys\nfolder=Path(__file__).resolve().parent\nsys.path.insert(0,str(folder))\nfrom pod_models import build\nbuild('${a.id}',folder)\n`);
 await fs.copyFile(`C:/Users/jonas/AppData/Local/Temp/codex-clipboard-${a.reference}.png`,folder+'/references/user-photo.png');
 if(a.id!=='gh_recessed_lounge')await fs.copyFile('C:/Users/jonas/AppData/Local/Temp/codex-clipboard-17f6b711-ab94-407c-824b-147fa3180491.png',folder+'/references/user-wide-lounges.png');
 m.displayName=a.name;m.source.mode='procedural';m.source.recipe=folder+'/build.py';m.palette={storage:'texture',colors:palette};
 m.texturePalettes=['palette','fabric','warm_light'].map(kind=>({material:a.id+'_'+kind,size:[64,4],roles:Object.fromEntries(Object.entries(palette).map(([role,color],i)=>[role,{color,rect:[i*4,0,4,4]}]))}));
 m.budgets={triangles:30000,meshes:10,materials:3,textures:3,textureSize:64,bones:0};m.exportSettings={paletteSampler:'linear'};
 m.contract.grounded=true;m.contract.groundY=0;m.contract.groundTolerance=.004;m.contract.anchors=['anchor_seat',a.id==='gh_bookshelf_pod'?'anchor_books':'anchor_opening'];m.contract.dimensions={min:a.size.map(v=>v-.06),max:a.size.map(v=>v+.06)};
 m.references=[{path:folder+'/references/user-photo.png',provenance:'User attached GitHub office photo, 2026-09-30; copied without changes. Photography guides shapes/materials only, never used as runtime texture.'}];
 if(a.id!=='gh_recessed_lounge')m.references.push({path:folder+'/references/user-wide-lounges.png',provenance:'User attached wide reading-lounge photo, 2026-09-30; unchanged design reference, not shipping texture.'});
 await fs.writeFile(file,JSON.stringify(m,null,2)+'\n');
 await fs.writeFile(folder+'/decisions.md',`# ${a.name}\n\nUser direction, 2026-09-30: add bookshelf/work lounges shown in the three supplied reference photos. The phrase about preferring windows was explicitly corrected by the user as a typo and is ignored; rounded rectangular openings are nevertheless governing pictured design landmarks.\n\n## Primary reference and landmarks\n\n${a.brief}\n\nActual office dimensions are unavailable. Authored X/Y/Z target ${a.size.join(' × ')} metres is a modular interpretation, with centered X/Z origin, ground Y=0 and bookshelf/front portal facing +Z. The bookshelf side niche faces -X. All portals are genuine negative space; no flat dark panel pretends to be a opening. References remain archival-only; books, fabric, bricks and fittings are independently modeled low-poly shapes.\n\n## Materials and interfaces\n\nTiny packed 64×4 atlas reused across wood, rough fabric and restrained warm emissive materials; no photograph textures. Warm oak retains the established GitHub kit family, cream upholstery follows the references. Three static environment assets, no animation or gameplay changes. Anchors identify seat and front book/opening location. Blender is the editable source and guarded export owns GLB delivery. User artistic acceptance remains pending.\n`);
 console.log(a.id+' recipe and reference brief installed');
}

