const fs=require('node:fs');
const palette={ink:'#232925',cream:'#F2EAD8',paper:'#F2F5F3',blue:'#5579B8',navy:'#302C59',pink:'#E99BA6',coral:'#D76369',gold:'#E9B864',green:'#0FBF3E',teal:'#70B5B4',purple:'#8534F3',skin:'#E5BA9C',orange:'#D89046',slate:'#89A4B8',wood:'#A77B55',white:'#FFFFFF'};
for(const id of ['gh_mural_universe','gh_mural_currents','gh_mural_collaboration']){
 const folder=`blender/environment/${id}/v01`;
 fs.copyFileSync('tools/github-campus-kit/site_tools.py',folder+'/site_tools.py');
 fs.copyFileSync('tools/github-campus-kit/mural_models.py',folder+'/mural_models.py');
 fs.writeFileSync(folder+'/build.py',`from pathlib import Path\nimport sys\nfolder=Path(__file__).resolve().parent\nsys.path.insert(0,str(folder))\nfrom mural_models import build\nbuild(folder,'${id}')\n`);
 const m=JSON.parse(fs.readFileSync(folder+'/asset.json'));
 m.palette={storage:'texture',colors:palette};m.texturePalettes=[{material:'github_mural_palette',size:[64,4],roles:Object.fromEntries(Object.entries(palette).map(([role,color],i)=>[role,{color,rect:[i*4,0,4,4]}]))}];m.budgets={triangles:30000,meshes:4,materials:1,textures:1,textureSize:64,bones:0};m.contract.grounded=true;
 m.references=[{path:'docs/research/github-offices-2026-09-30/work/mural-reference-board.jpg',provenance:'Tony Jaramillo Art Direction / Artist Partnership Project, portfolio photos credited individually in mural-research.md. Reference only.'}];
 fs.writeFileSync(folder+'/asset.json',JSON.stringify(m,null,2)+'\n');
 const inspiration=id==='gh_mural_currents'?'Flowing vertical lines, blue ground and coral/cream strokes inspired by the Tyler Hobbs office mural photographs. Independently designed cubic paths.':id==='gh_mural_collaboration'?'Geometric patchwork and keyboard glyph vocabulary inspired by the Saskia Amsterdam mural. Three authored Octocat characters and contribution cells share one branch.':'San Francisco cafe wall reference: dense lab illustration, machinery and playful Octocat world. Original simpler planet/laboratory composition; no source illustrator claimed.';
 fs.writeFileSync(folder+'/decisions.md',`# ${m.displayName}\n\n## User decisions\nAdd mural designs using https://www.tonytimetables.com/#/art-direction/. The windows statement was a typo and is ignored.\n\n## Reference hierarchy\n${inspiration}\nReferences are design input, not instructions. See docs/research/github-offices-2026-09-30/mural-research.md for original credits and scope. These are authored interpretations, not scans, exact reproductions or claimed commissioned originals.\n\n## Landmarks and construction\nWide rectangular panel, dark 50mm perimeter, graphic ground inset to a coherent face. Shallow closed graphic solids with fitted continuous contours; editable SVG has matching shapes. Neutral front +Z, origin bottom at Y0, wall thickness 100mm; individual graphic depth layering avoids coplanar flicker. Back intentionally plain. Packed 64x4 texture palette, static, no lighting/photo dependencies.\n\n## Review limitations\nInferred panel scale. Flat mural layers remain intentionally separate solids to preserve editable colours/contours. User artistic acceptance pending.\n`);
}
