import {readFile,writeFile} from 'node:fs/promises';
import {findAsset,hash} from '../asset-pipeline/contracts.mjs';
import {reviewAsset} from '../asset-pipeline/visual-review.mjs';
const notes={
gh_mural_universe:['The San Francisco cafe reference establishes an illustrated laboratory universe. This original graphic uses a large Octocat, planets, circuit contours and a row of machines; it deliberately simplifies the dense original wall.','Graphic contours are closed shallow solids on a continuous framed wall; nose/eyes and smile sit above the face. Corrected centre tentacle to a curling path instead of a folded vertical stroke. Oblique view retains fitted depth and uninterrupted panel boundary.','Planet, Octocat and machine row remain distinct at phone framing. The larger character provides an identifiable focus even when tiny details simplify.'],
gh_mural_currents:['Blue ground and varied coral/cream/blue flowing lines follow the vocabulary of the portfolio’s Tyler Hobbs office mural photographs. These paths are independently authored; no tracing or source painting is embedded.','Thirty-five coherent stroke outlines have fitted ends and remain attached to the backing. Crossing paths are intentional graphic overlaps; flat rear is closed and front layers have explicit depth separation.','Line rhythm and contrasting dark background read at phone width; sparse gold nodes and the bottom branch glyph provide accents without dominating the pattern.'],
gh_mural_collaboration:['The Saskia office-art reference informs patchwork colour and keyboard-symbol rhythm. The three original related Octocats and contribution cells add clear GitHub identity; this is an interpretation, not the commissioned mural itself.','Repeated characters share aligned facial landmarks and deliberately varied face colours. Corrected centre tentacle curls on all three instances. Graphic is seated on one continuous rectangular panel, and rear remains plain.','Three characters, code brackets and tiled contribution rhythm survive phone framing. Their large silhouettes remain separate from the lighter background tiles.']
};
for(const [id,n] of Object.entries(notes)){
 const a=await findAsset(id,'v01');await reviewAsset(a,{initialize:true});const folder=`blender/environment/${id}/v01`,file=folder+'/validation/visual_review.json',r=JSON.parse(await readFile(file));
 r.scope='model';r.reviewedAt=new Date().toISOString();['referenceFidelity','construction','readability'].forEach((key,i)=>r.checks[key]={status:'passed',findings:n[i]});
 r.checks.motion={status:'not_applicable',findings:'Static wall-mounted graphic panel, no rig or clips requested.'};
 r.secondPass={status:'passed',findings:'Finished GLB compared again with the six reference photographs after centre-tentacle correction on character panels. Front and close-up retain consistent face/ear landmarks; oblique has no detached graphic edges; rear is intentionally plain and closed; phone captures were reframed after viewport reduction. No additional scoped construction repair remains.'};
 r.userAcceptance={status:'pending',note:'Author review completed; user artistic acceptance is not inferred.'};r.limitations=['Original simplified graphic interpretations, not replicas of commissioned paintings.','Panel dimensions are authored; source photographs are reference-only.'];
 r.evidence=[];for(const view of ['front','iso','rear','detail','phone']){const path=folder+'/validation/inspector-'+view+'.png';r.evidence.push({path,sha256:hash(await readFile(path)),view});}
 await writeFile(file,JSON.stringify(r,null,2)+'\n');const result=await reviewAsset(a);if(!result.ready)throw Error(JSON.stringify(result));console.log(id+': final hash-bound author review ready');
}
