const fs=require('node:fs');const crypto=require('node:crypto');const {spawnSync}=require('node:child_process');
const assets=JSON.parse(fs.readFileSync('tools/github-campus-kit/plan.json')).assets.filter(a=>a.owner==='props');
const observations={
gh_workstation:['Solid pale oak top, iron trestles and dark monitor match MASH/warehouse material cues; monitor/chair and green laptop are original readable fittings.','Monitor seated on a visible stem/base; separate keyboard and cup clear the top. Rear view exposes coherent iron frame and planted chair feet.','Phone oblique view clearly separates monitor, chair, pale tabletop and laptop; small code lines remain secondary.','Second assessment confirms armrests fit the chair, monitor clears the chair back, and desktop props retain separate silhouettes. No structural repair required.'],
gh_meeting_set:['Mahogany slab and broad trestles follow documented communal-table material direction, with burgundy upholstery from the quieter expansion. Eight-chair layout is interpreted.','Chair spacing repeats evenly, supports contact ground, trestle beam sits beneath the thick slab; oblique and reverse views show intentional seated overlaps.','At 390px the wide table and paired chair rhythm read as a meeting ensemble; laptops and cups remain quiet secondary accents.','Rechecked chair rows from opposite side, slab thickness and feet under equal neutral framing. Main and supporting forms remain legible; no repair needed.'],
gh_library:['Pale oak bookshelf, true curved central reading niche, books and burgundy carrel wings capture Rapt expansion landmarks. It is a compact reusable interpretation rather than an exact furniture copy.','Real segmented closed arch solids preserve central negative space; rear panels intentionally close seated niches. Side stacks have distinct shelves/books; carrel wings have consistent depth.','Phone framing retains central blue niche, burgundy paired screens and book-filled outside stacks. Wood outline and curved opening identify the unit.','Repaired initial empty side bays by adding vertical book stacks and narrower seat cushions. Finished export rechecked front/oblique/reverse and phone: arch remains clear, new shelf depth does not cross the carrel wings.'],
gh_cafe_bar:['Warm solid oak, vertical boarded counter, four iron stools, light rear wall, bottle shelving and espresso block reflect documented industrial cafe references.','Counter front panel rhythm is consistent, stool metal feet meet ground and seat under a continuous top; shelves fit the rear tile wall, bottle necks are connected.','At phone size the long oak bar, dark stools and repeated bottle shelves remain distinct; fine bottle labels were deliberately omitted.','Second assessment checked rear wall closure, stool repeat centers and top edge from opposite view. No floaters or unintended counter/shelf crossings observed.'],
gh_lounge:['Blue/purple softened upholstered furniture and wood stump table reference the expanded office lounge and earlier wood/black lounge material cues.','Feet support sofa bodies; cushion divisions remain visibly separate, broad arms fit the seat depth. Reverse shows a continuous back rather than exposed facing panels.','At 390px blue sofa, purple chair and contrasting circular table are recognizable through silhouette and color.','Second review confirms seat subdivisions do not form sliver gaps, table clears sofas and leg contact remains coherent; no repair needed.'],
gh_pendant:['Black warehouse suspension, hanging cables, dark shades and warm visible bulbs capture documented industrial pendant lamps. Three-lamp straight rig is modular interpretation.','Each cable joins top beam and shade. Warm rim seats around the shade edge, bulb remains within shade mouth, and no cable crosses the neighboring shade.','Initial phone oblique result hid bulbs; added warm emissive rim now reads against the dark Inspector background while remaining restrained.','Repaired warm rim/emitter and re-exported with explicit two-material/two-texture budget. Rechecked front and phone export: hanging rhythm and shade silhouette preserved, illuminated edges now legible.'],
gh_thinktocat:['Reference governing landmarks checked against installed Thinktocat photo: broad round head, cat ears, lowered face, chin-rest curl, crossed tentacle, seated feet and white tapered plinth. Bronze shape is original low-poly interpretation, not exact sculptural duplication.','Front/close/oblique views show chin-support tentacle seated beneath muzzle and crossed tentacle across body. Rear shows swept curved tail and rock seat, feet rest on plinth.','At phone size the round cat head, paired ears, thoughtful pose and chalk plinth remain clear. Bronze faceting is deliberate stylization.','Second close review compared major head/body ratio and chin/elbow landmarks with source. Lowered eyelids and curved extremities preserve thoughtful expression; simplified bronze surface omits source patina and sculptural microdetail.'],
gh_sign:['Current official GitHub white vector lockup sampled directly from official SVG paths, keeping logotype/Invertocat layout and aspect ratio. Original monument frame uses neutral black and restrained green base line.','Extruded logo outlines sit just proud of graphite slab, closed slab and stone footing are fitted. Oblique view preserves holes in letters and Invertocat silhouette; rear is intentionally blank.','White lockup and black backing read clearly at 390px with broad clear space around the mark.','Second enlarged export view checked wordmark holes, pictogram proportions and slab edge. Curved paths remain faithful at intended model scale, no invented typeface substitute.'],
gh_contribution_art:['Hundreds of green suspended plates, wire lattice, depth variation and front cat negative-space follow IA atrium installation logic. Motif is an interpreted cat silhouette; not the source exact Mona image or kinetic system.','Plate solids have authored thickness; transverse wire segments connect varied depth to hanging lines. Oblique view exposes open center and depth field, reverse retains coherent supports.','At phone size grid reads as floating contribution artwork and central cat-shaped absence; from oblique angles it intentionally becomes more abstract.','Second front/oblique assessment checked plate rhythm and grid depths against source contact sheet. Solid opaque plates simplify polycarbonate deliberately; no floating plates or unintended large opaque background plane.'],
gh_roof_furniture:['Circular concrete chess/pedestal table, timber/concrete benches and planted concrete basin reference GitHub roof furniture cues. Chess pieces and paired bench arrangement are original.','Table pedestal reaches ground; chessboard inlay is intentionally just above concrete surface, two bench supports and fitted back rails visible in reverse.','Phone view distinguishes checkerboard top, two warm benches and teal planter foliage without requiring readable small pieces.','Second assessment checked circular top edge, bench feet and planter/table clearance from opposite view. All pieces remain separate and mechanically plausible in this stylization.']};
for(const a of assets){
 const folder=`blender/environment/${a.id}/v01/validation`,file=folder+'/visual_review.json';
 let r=spawnSync(process.execPath,['tools/asset-pipeline/asset.mjs','review',a.id,'--init'],{encoding:'utf8',windowsHide:true});if(r.status)throw Error(r.stdout+r.stderr);
 const review=JSON.parse(fs.readFileSync(file));const o=observations[a.id];review.scope='model';review.reviewedAt=new Date().toISOString();
 for(const [i,k] of ['referenceFidelity','construction','readability'].entries())review.checks[k]={status:'passed',findings:o[i]};
 review.checks.motion={status:'not_applicable',findings:'Intentionally static environment ensemble; no rig, animation, root motion or gameplay behavior requested.'};review.secondPass={status:'passed',findings:o[3]};
 review.evidence=[];for(const view of ['front','iso','rear','inspector-phone',...(['gh_library','gh_thinktocat','gh_sign','gh_contribution_art'].includes(a.id)?['inspector-close']:[])]){const p=folder+'/'+view+'.png';review.evidence.push({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),view});}
 review.userAcceptance={status:'pending',note:'User requested production; no artistic acceptance of this specific revision has been given.'};review.limitations=['Research-informed modular interpretation; furniture measurements are inferred, not certified as-built specifications.'];
 if(a.id==='gh_sign')review.limitations.push('Official GitHub logo/trademarks remain GitHub property; downloaded originals retained for provenance.');
 if(a.id==='gh_contribution_art')review.limitations.push('Static opaque plates and interpreted cat silhouette replace the real installation translucent polycarbonate and specific Mona perspective.');
 fs.writeFileSync(file,JSON.stringify(review,null,2)+'\n');r=spawnSync(process.execPath,['tools/asset-pipeline/asset.mjs','review',a.id],{encoding:'utf8',windowsHide:true});
 fs.writeFileSync(folder+'/author-review-log.txt',r.stdout+r.stderr);console.log(a.id+': author review '+(r.status===0?'complete':'failed'));if(r.status)throw Error(r.stdout+r.stderr);
}
