import {readFile,writeFile} from 'node:fs/promises';
import {findAsset,hash} from '../asset-pipeline/contracts.mjs';
import {reviewAsset} from '../asset-pipeline/visual-review.mjs';
const assessments={
 gh_floor_wood:['The photographed warm warehouse boards are translated into staggered oak geometry, with intentionally simplified grain and a lighter game palette.','Thin slab, board edges and staggered end seams remain consistent; no lifted boards or exposed unfilled edge cuts in oblique view.','Board rhythm reads in the 390px Inspector view; thin rear silhouette is appropriate for a floor module.','Second comparison with the open-office photo confirms the warm plank vocabulary; the brighter oak is an explicit stylization.'],
 gh_floor_paving:['Authored campus landscaping addition: concrete slab and neutral large-format paving support the office kit. Not a claim about surveyed Brannan sidewalks.','Six-metre slab has even four-by-four inset paving with a continuous bed and small intentional seams.','Slab boundary and joints remain visible in phone framing; restrained variation avoids competing with buildings.','Second oblique/reverse check confirms a flat reusable module with no projecting corners or accidental open grout bed.'],
 gh_floor_hex:['The original cafe hex-floor motif is represented as real individually cut polygon tiles, without a copied photograph.','Hexagons clip cleanly to the square module boundary; visible dark grout is deliberate and the slab stays continuous.','White hex pattern and sparse slate accents remain legible in close oblique and phone views.','Second view check confirms clipping preserves the square outline; no floating edge triangles were visible.'],
 gh_timber_frame:['Restored wood posts, iron collars and exposed joist hierarchy follow the open-office structural photograph; bay dimensions are authored.','Knee braces seat into post and girder faces; iron shoes rest at the origin and secondary joists sit below the top beam surface.','Strong post/beam outline and open centre survive phone-scale framing; slender braces do not obscure the main structure.','Second comparison checks repeated joist spacing, brace seats and rear symmetry. No additional construction repair was needed.'],
 gh_stairs:['Industrial metal and oak stairs echo the container/stair references; rise is an authored five-metre module, not a surveyed stair.','Twenty treads have continuous stringers, nosings, rail supports and a top landing; reverse view exposes the open risers and fitted support posts.','The stair direction and oak/steel separation read at phone width, with a continuous diagonal rail silhouette.','Second oblique/rear assessment confirms support and rail continuity. Upper guard height is correctly additional to the five-metre rise.'],
 gh_planter:['Concreteworks planter and warm courtyard material vocabulary guide the concrete body; broad foliage is a stylized campus addition.','Separate rim sections meet without floating corners; dark soil is recessed and shrub masses grow above the soil rather than through the exterior.','Chalk rim, grey body and green/teal foliage stay distinct in the phone view.','Second front/oblique check finds even rim seats and a compact silhouette; no visible soil/body gaps.'],
 gh_tree:['Original landscape model extends the campus kit using Tower foliage colours and official GitHub green accents. It does not reproduce a documented GitHub tree.','Trunk tapers into three seated branches, asymmetric crown masses overlap intentionally, and the planting ring contacts the ground.','Broad angular crown and slim trunk remain readable on phone; a few brighter leaf masses provide orientation.','Second reverse check verifies branch attachment and ground ring. Crown asymmetry is deliberate, with no detached leaves.'],
 gh_courtyard:['Contribution graph geometry is an authored garden interpretation paired with concrete/wood bench vocabulary from the office terrace sources.','Raised cells are seated in a continuous turf bed; wood planks span two concrete piers and lanterns have fitted panes and bases.','The 14-by-7 green cell field reads as contribution-inspired paving at phone scale; benches stay outside its main field.','Second oblique/reverse check confirms perimeter seating and lantern seats. This is a garden, not a flat traversable floor module.'],
 gh_membrane_wall:['Rapt Studio and NEW/LIGHT references govern the continuous curved white meeting-wall vocabulary. Wall thickness is 0.3048m, matching the documented one-foot assembly; curve footprint is inferred.','Twenty-four joined curve segments keep continuous inner/outer boundaries and a closed top; mounting feet seat under the sweep. Repaired unused UV channels so both groups bind one exact named palette material.','White curved silhouette and shallow end thickness read in oblique/rear and phone views. Low emission suggests the luminous membrane without expensive glass sorting.','Second reference comparison confirms the long curved white shape and clean edge profile. It is an opaque luminous approximation, not a membrane engineering simulation.'],
 gh_ceiling_services:['Exposed silver ducts and suspended linear lights follow the original warehouse open-office photograph, with an authored six-metre bay interface.','Initial review found an unconnected outlet and a floating flange; corrected to a continuous quarter-turn mesh and properly aligned outlet/flanges. Suspension ties end at mount shoes.','Large duct elbow and two black light housings remain readable in phone view; white underside diffusers separate from the dark fittings.','Second underside/reverse inspection checks the corrected continuous elbow, flange seats and suspension attachment. No isolated pipe hardware remains.'],
 gh_indoor_park:['The photographed indoor park, turf and wooden Adirondack chairs guide this six-by-four-metre original seating module.','Slatted inclined seats join splayed legs, broad armrests and back supports; turf sits in a floor tray and planter is seated at the edge.','Chair profiles, wood walkway and green inset remain distinct in close oblique and phone frames.','Second reverse/side comparison confirms the reclining chair silhouette and fitted supports. Plant geometry is deliberately faceted and module dimensions are inferred.']
};
for(const [id,notes] of Object.entries(assessments)){
 if(process.argv.slice(2).length&&!process.argv.slice(2).includes(id))continue;
 const item=await findAsset(id,'v01');await reviewAsset(item,{initialize:true});
 const folder=`blender/environment/${id}/v01`,file=folder+'/validation/visual_review.json';const r=JSON.parse(await readFile(file));
 r.scope='model';r.reviewedAt=new Date().toISOString();
 for(const [index,key] of ['referenceFidelity','construction','readability'].entries())r.checks[key]={status:'passed',findings:notes[index]};
 r.checks.motion={status:'not_applicable',findings:'Static modular office/campus scenery. No animation was requested or authored.'};
 r.secondPass={status:'passed',findings:notes[3]+' Phone capture was explicitly reframed after the viewport width changed, then checked for complete-model visibility.'};r.userAcceptance={status:'pending',note:'Author self-review completed; no artistic acceptance is inferred from the user request.'};
 r.limitations=['Stylized, inferred dimensions; not a measured as-built reconstruction.'];
 r.evidence=[];for(const view of ['iso','rear','inspector-detail','inspector-phone']){const path=folder+'/validation/'+view+'.png';r.evidence.push({path,sha256:hash(await readFile(path)),view});}
 if(id==='gh_ceiling_services'){const path=folder+'/validation/inspector-underside.png';r.evidence.push({path,sha256:hash(await readFile(path)),view:'underside'});}
 await writeFile(file,JSON.stringify(r,null,2)+'\n');
 const result=await reviewAsset(item);if(!result.ready)throw Error(JSON.stringify(result));console.log(id+': author review current and complete');
}
