import fs from 'node:fs/promises';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
const findings={
 gh_bookshelf_pod:{referenceFidelity:'Compared supplied close and wide office photographs to current front, left, oblique and phone exports. Tall warm oak end-cap has dense varied book rows, a clear sculptural display shelf and separate full circular wood disk with a warm halo. Side reading portal has rounded rectangular corners, an actual recessed cushion, diamond upholstery and black lamp. Human occupant and literal book titles are intentionally omitted.',construction:'Closed ring geometry forms a true -X side opening; padded ring sits within the oak frame. Cabinet book stack remains on +Z and ends before the shifted side portal. Reading seat is physically recessed with a fitted structural and quilted back. Bust clears the shelf above, full circular halo clears roof and book tops. Front/left/close and blank rear export show supported panels and coherent shelf depth.',readability:'At 390px the rounded opening, diamond lining and hanging lamp remain distinct; front view identifies the bookcase and halo. Default positive-X oblique faces the closed side, so the left side and a left oblique were also examined. Book labels remain intentionally secondary.',second:'Initial export exposed upper books overlapping the halo and a shelf clipping the bust. Removed the surplus upper row, lowered/reduced halo and shortened bust. Shifted side opening behind front shelving, tightened quilting seam spacing and fitted a shallower seat back. Re-exported and independently rechecked current front/left/reverse/oblique/close and 390px renders against both supplied photos; halo is fully visible, niche is genuine and shelving has clear structural separation.'},
 gh_worklounge_pod:{referenceFidelity:'Wide supplied lounge photo governs broad horizontal opening, warm oak enclosure, rounded corners, visible brick back, cream lining and long cushion. Current export contains a true 4.78m-wide rounded rectangular portal, three tailored cushions, cream padded sides, a wall lamp and a quiet book ledge. Oak enclosure and brick contrast follow the photo.',construction:'Continuous ring has no crossing bars or fake dark opening. Deep side/roof panels, inset padded ring, layered brick backing and seat cushions fit within the shell. Diamond upholstery is mesh geometry with narrow fabric seams. Front, reverse and close oblique show intentional wall closure and full-depth seat; small books clear the seating edge.',readability:'At 390px the wide horizontal rounded opening and long pale seat silhouette remain recognizable; brick and quilt patterns are secondary. The large opening reads distinctly from the earlier arch-shaped library.',second:'First review found square pillow outlines and coarse, checker-like quilting. Rebuilt pillow faces with rounded rectangle profiles and tightened quilt spacing. Current exported front/oblique/reverse/close and phone views were assessed again with the wide photo visible; the open portal proportions, seat separation and tucked padded edge remain clean.'},
 gh_recessed_lounge:{referenceFidelity:'Supplied dark nook photograph governs graphite framing, raised oak step, brown couch, loose pillows, striped draped throw, small folding side table, lantern and exposed warehouse timber. These landmarks remain in the current export; laptop and cup express its work lounge use without adding people.',construction:'Deep graphite side frames and top surround a genuinely open front. Sofa base supports separated seat cushions and loose pillows; throw wraps across the cushion and front edge with short tassels. Crossed table legs seat under a small tabletop, lantern cage meets its base/cap, laptop screen is supported by its base. Step emission is a fitted narrow source-authored strip.',readability:'At 390px the dark frame, warm platform, brown seat, blue laptop and high-contrast throw remain clear. Small lantern and folding details are secondary close-view details; overall silhouette reads as a cozy recessed work lounge.',second:'After first pass, replaced boxy loose-pillow faces with rounded profiles and adjusted repeated seat centers to remain within the couch. Reviewed the finished front/oblique/reverse/close and phone exports against the photo again; pillows clear the frame, throw has a consistent drape, and table feet rest on the raised platform.'}
};
for(const [id,o] of Object.entries(findings)){
 const folder=`blender/environment/${id}/v01`,file=folder+'/validation/visual_review.json';let p=spawnSync(process.execPath,['tools/asset-pipeline/asset.mjs','review',id,'--init'],{encoding:'utf8',windowsHide:true});if(p.status)throw Error(p.stdout+p.stderr);
 const r=JSON.parse(await fs.readFile(file,'utf8'));r.scope='model';r.reviewedAt=new Date().toISOString();
 for(const key of ['referenceFidelity','construction','readability'])r.checks[key]={status:'passed',findings:o[key]};r.checks.motion={status:'not_applicable',findings:'Static environment furniture. No animation, rig, moving root or gameplay behavior requested.'};r.secondPass={status:'passed',findings:o.second};
 r.evidence=[];for(const view of ['front','iso','rear','left','close','phone']){const imagePath=folder+`/validation/inspector-${view}.png`;r.evidence.push({path:imagePath,sha256:crypto.createHash('sha256').update(await fs.readFile(imagePath)).digest('hex'),view:view==='phone'?'390px-phone':view,mode:'shaded'});}
 r.userAcceptance={status:'pending',note:'User requested these additions; no explicit artistic acceptance of the delivered revision has been given.'};r.limitations=['Modular low-poly interpretation with inferred dimensions, not a measured replica of GitHub furniture. Books and optional bust use enlarged simple shapes; fabric has geometric quilting rather than a photo texture.'];
 await fs.writeFile(file,JSON.stringify(r,null,2)+'\n');p=spawnSync(process.execPath,['tools/asset-pipeline/asset.mjs','review',id],{encoding:'utf8',windowsHide:true});await fs.writeFile(folder+'/validation/author-review-log.txt',p.stdout+p.stderr);if(p.status)throw Error(p.stdout+p.stderr);
 let d=await fs.readFile(folder+'/decisions.md','utf8');d=d.replace('six shelf levels','five shelf levels').replace('side portal 1.62m wide','side portal 1.50m wide').replace('at 2.855m','at 2.77m');d+='\n## Author review of delivered model\n\n'+o.second+'\n\nCurrent hash-bound assessment: validation/visual_review.json. Technical delivery and author construction/reference/readability checks passed; explicit user artistic acceptance remains pending.\n';if(id==='gh_bookshelf_pod')d+='\nReserved display shelf spot for tiny secret Octocat: local X+.52, Z+.93, Y1.6125. The bust stays centered and leaves the right shelf area clear.\n';await fs.writeFile(folder+'/decisions.md',d);console.log(id+' author review passed');
}
