import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
const dir='blender/towers/copilot_security/v01';
const m=JSON.parse(await fs.readFile(dir+'/asset.json'));
if(m.revision!==4)throw Error('Historical r4 review script; use record-contour-review.mjs for the corrected contour.');
const r=JSON.parse(await fs.readFile(dir+'/validation/visual_review.json'));
r.reviewedAt=new Date().toISOString();r.scope='model';
r.checks.referenceFidelity={status:'passed',findings:'Compared supplied six-view and shape sheets to front, side and isometric blockout, then finished export. Width/height 1.097 against approximately 1.12 in the illustrated front. Rounded head-only body, face opening, paired octagonal pods, angular pale-blue goggles, white brow, cyan eyes, centered shield, arched crest, three rear vents and only a character-left scanner are retained. Disagreeing illustrated depth is reconciled in the brief; low-poly bevels are intentionally more faceted than the concept rendering.'};
r.checks.construction={status:'passed',findings:'Inspected actual Inspector close oblique, reverse, opposite side and underside. Initial non-planar concave chin faces caused visible white/blue crossing; split the bowed chin and lip at the center plane. Seated the crest and raised its dark supports to remove partial triangles through the casing. Added a fitted blue housing behind the brow to close its upper gap. Final rings, scanner saddle and optics are seated, rear vents are recessed and evenly spaced, and no open accidental through-gap or flickering overlap was visible in the inspected views.'};
r.checks.readability={status:'passed',findings:'Viewed final export at 390-pixel phone width and the Inspector small silhouette test (roughly 80-pixel model). Goggles, paired cyan eyes, white chin band, pod ring and left scanner remain readable. Shield reduces to a clear white badge at the smallest scale; its small bevel and rear vent depth are close-view detail.'};
r.checks.motion={status:'not_applicable',findings:'Model-only request. No authored animations or placeholder clips. Baseline animation remains pending the model-first handoff.'};
r.secondPass={status:'passed',findings:'Reassessed the final revision 4 after chin, crest/support and brow-seat repairs. The close Inspector view shows a continuous white chin lip, a supported crown and a filled brow attachment. Reverse and underside preserve enclosed body and symmetric pod seats. Rechecked front silhouette, scanner asymmetry, rear vent spacing and small phone view. Source and runtime hashes agree with the Inspector note; technical export is 2648 triangles, two materials, two texture instances from one packed 32x4 image.'};
r.evidence=r.evidence.filter(e=>['iso','front','side','rear'].includes(e.view));
for(const name of ['inspector_iso','inspector_detail','inspector_left','inspector_rear','inspector_bottom','inspector_phone','inspector_small']){
 const path=dir+'/validation/'+name+'.png';
 r.evidence.push({path,sha256:createHash('sha256').update(await fs.readFile(path)).digest('hex'),view:name});
}
r.userAcceptance={status:'pending',note:'New model supplied for user review; no artistic acceptance inferred.'};
r.limitations=['Model-only milestone: rig and baseline animations pending.','Illustrated reference highlights and soft bevels are interpreted with opaque low-poly geometry and a tiny palette.'];
await fs.writeFile(dir+'/validation/visual_review.json',JSON.stringify(r,null,2)+'\n');
const initial=(await fs.readFile(dir+'/decisions.md','utf8')).split('## User direction and scope')[0];
await fs.writeFile(dir+'/decisions.md',initial+`\n## Primary-form and completed review\n\nThe first blockout is retained in renders/blockout. Front, side and isometric\ncomparison established the body envelope and pod fit before final optics/badge.\nIts non-planar concave chin panel triangulated across the white lip; corrected\nwith planar half panels and added a central chin plate. Lowered the forward\nhelmet shoulder to expose the broad crest. The next close inspection found\npartly buried crest supports and an upper brow gap; raised the supports and\nadded a fitted blue brow housing. Final close, reverse, underside, phone and\nsmall views were personally inspected. See validation/visual_review.json.\n\nRevision ${m.revision}: runtime ${m.delivery.sha256}\nSource ${m.delivery.sourceHash}\nExport: 2648 triangles, two materials, one packed 32x4 image (two runtime texture\ninstances for shell/optics). Dimensions 2.584 x 2.355 x 2.056 m.\nTechnical validation and author review passed; explicit user acceptance pending.\nAnimations pending; ask at handoff before starting the baseline animation pass.\n\nValidation history: initial blockout check lacked a configured Playwright module;\nresolved using game/node_modules/playwright. First production contract lacked\npalette.colors; corrected with explicit role colors. Candidate then exceeded\nthe one-texture-instance budget because shell and optics create two instances\nof the same packed image; declared the actual two-instance contract. Both failed\ncandidates stayed outside runtime. Final guarded delivery passed.\n`);
console.log('Recorded current source/export review and model-first animation handoff.');
