import fs from 'node:fs/promises';
import {findAsset} from '../../../../../tools/asset-pipeline/contracts.mjs';
for(const [id,baseline] of [['copilot_octocat_2_0',8],['copilot_octocat_2_0_lowpoly',5]]){
 const item=await findAsset(id),m=item.data,folder=item.manifest.replace('/asset.json','');
 const record=JSON.parse(await fs.readFile(folder+'/validation/visual_review.json'));
 const inspector=JSON.parse(await fs.readFile(folder+'/validation/animation/review.json'));
 const states=JSON.parse(await fs.readFile(folder+'/validation/animation_states.json'));
 const rest=JSON.parse(await fs.readFile(folder+'/validation/animation_rest_audit.json'));
 if(![inspector,states,rest].every(r=>r.passed&&r.sha256===m.delivery.sha256&&r.sourceHash===m.delivery.sourceHash))throw Error('Stale/incomplete animation evidence');
 record.scope='animation';record.reviewedAt=new Date().toISOString();
 record.checks={
  referenceFidelity:{status:'passed',findings:'Applied the documented research direction: five supporting tentacles in Move, soft elastic weight, focused nonverbal maker gestures, a brief startled Hit and friendly recovery. No extra tail, humanoid torso, spoken acting or angry default. The two raised tentacles remain an upright rest pose choice. Timings are Tower choices, not official GitHub requirements.'},
  construction:{status:'passed',findings:'29 deform bones; exact source rest geometry/topology/UV/material/smoothing hashes. Runtime positions and UVs match the static milestone, embedded images and material definitions match, and normal differences stay below 0.0001. Reviewed exposed rear/side/underside bends: connected five-way skin junction, cup rows follow the skin, and the repaired rear/underside face boundary remains black. Correctives use skin triangle attachment and explicit Basis initialization.'},
  readability:{status:'passed',findings:'Reviewed the actual Inspector in normal, phone-width, ground/shadow and game-scale views. Focused reach, lowered five-limb walk and surprised recoil read separately; the face remains the dominant contrast cue. The low version retains 3,961 triangles and full cell coverage with three temporary cube fragments, for 3,997 combined triangles.'},
  motion:{status:'passed',findings:'Six changing clips at 24 fps. Reviewed starts, anticipation/action extremes, recovery and exact ends; normal playback of several loop cycles and both sides of joins; Idle/Work/Move/Hit selection; Place-to-Idle; replay, seek and unanimated Rest reset. Recovery-foot velocity and acceleration match stance at contact. 240 actual runtime walk samples give <2.73 mm stance gap and <0.006 mm penetration. Independent expression presets vary and reset. Root remains stationary, fitting anchors retain their rest seats and follow assigned bones. Place begins invisible and ends exactly at ready Idle; Resolve ends invisible. Verified deterministic seek, completed hold/replay, loops, phone shadows, effects disabled, phase-preserving reload, exhausted fragment budget and material restoration.'}
 };
 record.secondPass={status:'passed',findings:'Second author inspection of the final exports after repairing cup binding, exporting armature-driven facial channels, initializing every morph from Basis, and smoothing foot recovery speed. Rechecked focused facial layers and reactions on both meshes; underside/rear/side maximum walk bends; phone/game silhouettes; actual lifecycle endpoints and Rest reset. The Inspector timeline now retains fractional 24 fps endpoints exactly.'};
 record.evidence.push(...inspector.frames);
 record.userAcceptance={status:'pending',note:'User authorized this animation pass; visual acceptance of the resulting model/animation revision is separate and remains pending.'};
 record.limitations=[
  'Move is authored against 0.28 m/s forward travel; simulation remains responsible for position and speed. Blend idle/move over about 0.18–0.22 s to change between the raised ready pose and five-limb locomotion.',
  'Digital assembly/disintegration requires Tower’s shared createLifecycleEffect presentation renderer; a standalone GLB player shows only the authored full-size pose.',
  'The low-poly version permits only three temporary cubes to keep its model-plus-effect geometry under 4,000 triangles. Its cell reveal/disintegration shader remains complete.',
  'Runtime interpolation produces a maximum 2.73 mm stance gap between authored keys; this is below the reviewed game-scale threshold.'
 ];
 await fs.writeFile(folder+'/validation/visual_review.json',JSON.stringify(record,null,2)+'\n');
 const before=JSON.parse(await fs.readFile(folder+'/revisions/r'+baseline+'_before_mona_animation/asset.json'));
 const decision=`\n## Research-led animation applied — 2026-09-30\n\nUser authorization: “apply these to both 2.0 octocats”. This supersedes the\nresearch-only animation-pending status above. Preserved static model revision\n${baseline} in revisions/r${baseline}_before_mona_animation/ before rigging. Its source hash\nwas ${before.delivery.sourceHash}; runtime\n${before.delivery.sha256}. Model acceptance remains\npending and is separate from this explicit animation authorization.\n\nDelivered animation revision ${m.revision}: 29 deform bones, five independent elastic\ntentacle chains, stationary root, and six clips at 24 fps: idle (2.25 s), work\n(1.75 s), move (28/24 s), place and resolve (26/24 s each), hit (10/24 s).\nThe maker’s attentive inspection/reach/tap, brief surprise and optimistic\nrecovery apply the published personality direction. Upright rest still has\ntwo raised and three supporting tentacles; grounded locomotion uses all five.\nWalk is authored for 0.28 m/s, 78% stance and five phased contacts. Recovery\nvelocity/acceleration match stance; runtime stance gap is below 2.73 mm.\n\nIndependent facial targets and seven presets retain separate display control;\narmature properties drive the editable source and sampled GLB weight tracks.\nCup weights/correctives follow underlying skin triangles. Explicit Basis\ninitialization prevents inherited morph deformation. Rest source geometry,\nUVs, palette, smoothing and fitting origins are preserved. Runtime rest\npositions/UVs and embedded images/materials match; normal rounding is <0.0001.\nThe repaired peach-face boundary stays confined to the front hemisphere.\n\nTower Place assembles digital cells into ready Idle; Resolve reverses it and\nends invisible. ${id.endsWith('lowpoly')?'Three':'32'} temporary cubes fit the existing geometry budget:\n${m.animationDesign.maxCombinedTriangles.toLocaleString('en-US')} maximum model-plus-cube triangles. No gameplay\nposition, timing or outcomes are implemented by this art export. A standalone\nGLB viewer needs the shared lifecycle renderer for the full effect.\n\nReviewed actual Inspector phase/extreme/recovery/end frames and normal playback,\nloop joins, exposed bends, phone/game scale, shadows, seek/replay/Rest reset,\neffect-off fallback, exhausted cube budget, disposal and hash-preserving reload.\nSecond author review and guarded technical/review checks are hash-bound to:\nsource ${m.delivery.sourceHash},\nruntime ${m.delivery.sha256}.\nUser visual acceptance of this revision remains pending.\n\nSee ${id.endsWith('lowpoly')?'../../copilot_octocat_2_0/v01/animation.md':'animation.md'} for the animation interface\nand runtime integration notes; research is in docs/design/Mona_Octocat_Animation_Research.md.\n`;
 const decisionFile=folder+'/decisions.md',old=await fs.readFile(decisionFile,'utf8'),marker='\n## Research-led animation applied — 2026-09-30';
 await fs.writeFile(decisionFile,old.split(marker)[0]+decision);
}

