import fs from 'node:fs/promises';
import crypto from 'node:crypto';
throw Error('Historical revision 4 recorder; use finish_anatomy_review.mjs for revision 7.');
const folder='blender/towers/copilot_octocat_2_0/v01';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const baseline=JSON.parse(await fs.readFile(folder+'/validation/existing_octocats_baseline.json'));
for(const [id,b] of Object.entries(baseline)){
 if(hash(await fs.readFile(b.source))!==b.sourceHash || hash(await fs.readFile(b.runtime))!==b.runtimeHash)throw Error('Existing Octocat changed: '+id);
}
await fs.writeFile(folder+'/validation/existing_octocats_preserved.json',JSON.stringify({checkedAt:new Date().toISOString(),passed:true,assets:baseline},null,2));
const m=JSON.parse(await fs.readFile(folder+'/asset.json'));
const audit=JSON.parse(await fs.readFile(folder+'/validation/source_audit.json'));
if(audit.sourceHash!==m.delivery.sourceHash)throw Error('Source audit is stale');
const review=JSON.parse(await fs.readFile(folder+'/validation/visual_review.json'));
review.scope='model';review.reviewedAt=new Date().toISOString();
review.checks.referenceFidelity={status:'passed',findings:'Compared the official Octocat 2.0 brand illustration and unadorned MyOctocat SVG against primary front/side/isometric volumes and final Inspector front/oblique views. Preserved large rounded cat head, shallow forehead dip, fuller cheek lobes, thin upright torso, two arm tentacles, two broad feet and rear tail. Dark ear insets and open grin distinguish this version from the preserved Modern model. The references are posed three-quarter illustrations, so frontal symmetry and the waving rest pose are documented interpretations; no orthographic identity claim.'};
review.checks.construction={status:'passed',findings:'Raised the mouth away from the chin, removed the low central torso nub, supersampled the painted face edge and moved its projection seam away from the cheeks. Final face close-ups show seated shallow eye/iris/glint surfaces, inset ears and separate nose/whiskers. Rear and underside views expose continuous shoulder/leg/tail roots and grounded broad feet. Body and head are each one closed connected shell, with zero nonmanifold edges or degenerate faces in the source audit. Both packed textures are embedded; all 45 cups remain seated on the body.'};
review.checks.readability={status:'passed',findings:'Personally inspected the final shared Inspector at phone width and the small-silhouette setting. Large peach face, ear outline, upright stance and asymmetrical waving arm remain recognizable. Tongue, ear interiors, tiny glints and individual cups become secondary at small scale; no gameplay meaning relies on these details. Scale is baked to 1.80029 m and geometry is not rescaled by the viewer.'};
review.checks.motion={status:'not_applicable',findings:'Model-only milestone. No rig or authored clips; animation remains pending the model handoff and user authorization. Planned baseline is recorded in decisions.md.'};
review.secondPass={status:'passed',findings:'Reviewed revision 4 again after correcting revision 3 smile placement and face-colour edge. Close front confirms a peach chin margin below the smile; close oblique retains skull depth and cheeks without exposed stacked mask edges. Rear and underside expose five intended appendages and smooth joined roots. Rechecked phone and game-scale views; no remaining scoped attachment or proportion defect blocks this stylized model handoff. Inspector note hash matches the delivered GLB.'};
review.evidence=review.evidence.filter(e=>['front','side','iso'].includes(e.view)&&e.mode==='shaded');
const live=JSON.parse(await fs.readFile(folder+'/validation/inspector_evidence.json'));
if(live.sha256!==m.delivery.sha256)throw Error('Inspector evidence stale');
review.evidence.push(...live.evidence.map(({path,sha256,view})=>({path,sha256,view})));
review.userAcceptance={status:'pending',note:'Awaiting explicit feedback on the reviewed Octocat 2.0 model revision 4.'};
review.limitations=['Static sculpt: baseline animation, rig deformation and wardrobe fitting are pending.','74,142 triangles and 20 meshes retain the established Modern quality envelope; crowded-scene mobile performance has not been profiled.','Reference pose and perspective are interpreted; GitHub artistic approval is not asserted.'];
await fs.writeFile(folder+'/validation/visual_review.json',JSON.stringify(review,null,2)+'\n');
await fs.appendFile(folder+'/decisions.md',`\n## Completed model review — revision ${m.revision}\n\nPrimary blockout revision 2 was inspected in front, side and isometric runtime\nviews before fitting details. The broad rounded head, projecting cheek band,\ncontinuous arm roots and two-foot negative space followed the official base.\nShortened the low torso volume before detailing to avoid a central nub between\nthe legs. The first blockout candidate failed a width minimum intended for the\nwhiskered final form; the primary-form envelope was corrected and its replacement\npassed. Failed staging evidence is retained.\n\nRevision 3 review exposed a smile too close to the chin and a rough face-map\nboundary. Raised/reduced the smile, projected its interior on additional rings,\nsupersampled the face map and moved the UV projection seam away from the cheek\nedge. Revision 4 passed the second author review in the shared Inspector, including\nclose frontal/oblique, reverse, underside, phone and small-silhouette views.\n\nFinal: 74,142 triangles, 20 meshes, 2 materials, 2 embedded textures, 0 bones.\nDimensions: 1.45384 x 1.80029 x 0.80259 m. Both head/body shells are connected and\nclosed with zero degenerate faces; both support contacts are at zero height.\nForty-five shallow cups and nine anchors remain. Guarded validation reports no\nerrors or warnings. Inspector loaded hash ${m.delivery.sha256}.\nSource hash ${m.delivery.sourceHash}. Existing Octocat source/runtime hashes were\nrechecked and remain unchanged.\n\nUser model acceptance and animation authorization remain pending.\n`);
console.log(JSON.stringify({revision:m.revision,existingOctocatsPreserved:true,sourceAudit:true,reviewWritten:true}));
